# Chapter 7: Sequential Data

We studied numbers (cf., [Chapter 5](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/05_numbers.ipynb)) and textual data (cf., [Chapter 6](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/06_text.ipynb)) first, mainly because objects of the presented data types are "simple," for two reasons: First, they are *immutable*, and, as we saw in the "*Who am I? And how many?*" section in [Chapter 1](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/01_elements.ipynb#Who-am-I?-And-how-many?), mutable objects can quickly become hard to reason about. Second, they are "flat" in the sense that they are *not* composed of other objects.

The `str` type is a bit of a corner case in this regard. While one could argue that a longer `str` object, for example, `"text"`, is composed of individual characters, this is *not* the case in memory as the literal `"text"` only creates *one* object (i.e., one "bag" of $0$s and $1$s modeling all characters).

This chapter and [Chapter 8](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/08_mappings.ipynb) introduce various "complex" data types. While some are mutable and others are not, they all share that they are primarily used to "manage," or structure, the memory in a program. Unsurprisingly, computer scientists refer to the ideas and theories behind these data types as **[data structures](https://en.wikipedia.org/wiki/Data_structure)**.

In this chapter, we focus on data types that model all kinds of sequential data. Examples of such data are [spreadsheets](https://en.wikipedia.org/wiki/Spreadsheet) or [matrices](https://en.wikipedia.org/wiki/Matrix_%28mathematics%29)/[vectors](https://en.wikipedia.org/wiki/Vector_%28mathematics_and_physics%29). Such formats share the property that they are composed of smaller units that come in a sequence of, for example, rows/columns/cells or elements/entries.

## Collections vs. Sequences

[Chapter 6](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/06_text.ipynb#A-"String"-of-Characters) already describes the *sequence* properties of `str` objects. Here, we take a step back and study these properties on their own before looking at bigger ideas.

The [collections.abc](https://docs.python.org/3/library/collections.abc.html) module in the [standard library](https://docs.python.org/3/library/index.html) defines a variety of **abstract base classes** (ABCs). We saw ABCs already in [Chapter 5](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/05_numbers.ipynb#The-Numerical-Tower), where we use the ones from the [numbers](https://docs.python.org/3/library/numbers.html) module in the [standard library](https://docs.python.org/3/library/index.html) to classify Python's numeric data types according to mathematical ideas. Now, we take the ABCs from the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module to classify the data types in this chapter and [Chapter 8](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/08_mappings.ipynb) according to their behavior in various contexts.

As an illustration, consider `numbers` and `text` below, two objects of *different* types.

In [1]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]
text = "Lorem ipsum dolor sit amet, consectetur ..."

Among others, one commonality between the two is that we may loop over them with the `for` statement. So, in the context of iteration, both exhibit the *same* behavior.

In [2]:
for number in numbers:
    print(number, end=" ")

7 11 8 5 3 12 2 6 9 10 1 4 

In [3]:
for character in text:
    print(character, end=" ")

L o r e m   i p s u m   d o l o r   s i t   a m e t ,   c o n s e c t e t u r   . . . 

In [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#Containers-vs.-Iterables), we referred to such types as *iterables*. That is *not* a proper [English](https://dictionary.cambridge.org/spellcheck/english-german/?q=iterable) word, even if it may sound like one at first sight. Yet, it is an official term in the Python world formalized with the `Iterable` ABC in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module.

For the data science practitioner, it is worthwhile to know such terms as, for example, the documentation on the [built-ins](https://docs.python.org/3/library/functions.html) uses them extensively: In simple words, any built-in that takes an argument called "*iterable*" may be called with *any* object that supports being looped over. Already familiar [built-ins](https://docs.python.org/3/library/functions.html) include [enumerate()](https://docs.python.org/3/library/functions.html#enumerate), [sum()](https://docs.python.org/3/library/functions.html#sum), or [zip()](https://docs.python.org/3/library/functions.html#zip). So, they do *not* require the argument to be of a certain data type (e.g., `list`); instead, any *iterable* type works.

In [4]:
import collections.abc as abc

In [5]:
abc.Iterable

collections.abc.Iterable

As in the context of *goose typing* in [Chapter 5](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/05_numbers.ipynb#Goose-Typing), we can use ABCs with the built-in [isinstance()](https://docs.python.org/3/library/functions.html#isinstance) function to check if an object supports a behavior.

So, let's "ask" Python if it can loop over `numbers` or `text`.

In [6]:
isinstance(numbers, abc.Iterable)

True

In [7]:
isinstance(text, abc.Iterable)

True

Contrary to `list` or `str` objects, numeric objects are *not* iterable.

In [8]:
isinstance(999, abc.Iterable)

False

Instead of asking, we could try to loop over `999`, but this results in a `TypeError`.

In [9]:
for digit in 999:
    print(digit)

TypeError: 'int' object is not iterable

Most of the data types in this and the next chapter exhibit three [orthogonal](https://en.wikipedia.org/wiki/Orthogonality) (i.e., "independent") behaviors, formalized by ABCs in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module as:
- `Iterable`: An object may be looped over.
- `Container`: An object "contains" references to other objects; a "whole" is composed of many "parts."
- `Sized`: The number of references to other objects, the "parts," is *finite*.

The characteristical operation supported by `Container` types is the `in` operator for membership testing.

In [10]:
0 in numbers

False

In [11]:
"l" in text

True

Alternatively, we could also check if `numbers` and `text` are `Container` types with [isinstance()](https://docs.python.org/3/library/functions.html#isinstance).

In [12]:
isinstance(numbers, abc.Container)

True

In [13]:
isinstance(text, abc.Container)

True

Numeric objects do *not* "contain" references to other objects, and that is why they are considered "flat" data types. The `in` operator raises a `TypeError`. Conceptually speaking, Python views numeric types as "wholes" without any "parts."

In [14]:
isinstance(999, abc.Container)

False

In [15]:
9 in 999

TypeError: argument of type 'int' is not iterable

Analogously, being `Sized` types, we can pass `numbers` and `text` as the argument to the built-in [len()](https://docs.python.org/3/library/functions.html#len) function and obtain "meaningful" results. The exact meaning depends on the data type: For `numbers`, [len()](https://docs.python.org/3/library/functions.html#len) tells us how many elements are in the `list` object; for `text`, it tells us how many [Unicode characters](https://en.wikipedia.org/wiki/Unicode) make up the `str` object. *Abstractly* speaking, both data types exhibit the *same* behavior of *finiteness*.

In [16]:
len(numbers)

12

In [17]:
len(text)

43

In [18]:
isinstance(numbers, abc.Sized)

True

In [19]:
isinstance(text, abc.Sized)

True

On the contrary, even though `999` consists of three digits for humans, numeric objects in Python have no concept of a "size" or "length," and the [len()](https://docs.python.org/3/library/functions.html#len) function raises a `TypeError`.

In [20]:
isinstance(999, abc.Sized)

False

In [21]:
len(999)

TypeError: object of type 'int' has no len()

These three behaviors are so essential that whenever they coincide for a data type, it is called a **collection**, formalized with the `Collection` ABC. That is where the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module got its name from: It summarizes all ABCs related to collections; in particular, it defines a hierarchy of specialized kinds of collections.

Without going into too much detail, one way to read the summary table at the beginning of the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module's documention is as follows: The first column, titled "ABC", lists all collection-related ABCs in Python. The second column, titled "Inherits from," indicates if the idea behind the ABC is *original* (e.g., the first row with the `Container` ABC has an empty "Inherits from" column) or a *combination* (e.g., the row with the `Collection` ABC has `Sized`, `Iterable`, and `Container` in the "Inherits from" column). The third and fourth columns list the methods that come with a data type following an ABC. We keep ignoring the methods named in the dunder style for now.

So, let's confirm that both `numbers` and `text` are collections.

In [22]:
isinstance(numbers, abc.Collection)

True

In [23]:
isinstance(text, abc.Collection)

True

They share one more common behavior: When looping over them, we can *predict* the *order* of the elements or characters. The ABC in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module corresponding to this behavior is `Reversible`. While sounding unintuitive at first, it is evident that if something is reversible, it must have a forward order, to begin with.

The [reversed()](https://docs.python.org/3/library/functions.html#reversed) built-in allows us to loop over the elements or characters in reverse order.

In [24]:
for number in reversed(numbers):
    print(number, end=" ")

4 1 10 9 6 2 12 3 5 8 11 7 

In [25]:
for character in reversed(text):
    print(character, end=" ")

. . .   r u t e t c e s n o c   , t e m a   t i s   r o l o d   m u s p i   m e r o L 

In [26]:
isinstance(numbers, abc.Reversible)

True

In [27]:
isinstance(text, abc.Reversible)

True

Collections that exhibit this fourth behavior are referred to as **sequences**, formalized with the `Sequence` ABC in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module.

In [28]:
isinstance(numbers, abc.Sequence)

True

In [29]:
isinstance(text, abc.Sequence)

True

Most of the data types introduced in the remainder of this chapter are sequences. Nevertheless, we also look at some data types that are neither collections nor sequences but still useful to model sequential data in practice.

In Python-related documentations, the terms collection and sequence are heavily used, and the data science practitioner should always think of them in terms of the three or four behaviors they exhibit.

Data types that are collections but not sequences are covered in Chapter 8.

## The `list` Type

As already seen multiple times, to create a `list` object, we use the *literal notation* and list all elements within brackets `[` and `]`.

In [30]:
empty = []

In [31]:
simple = [40, 50]

The elements do *not* need to be of the *same* type, and `list` objects may also be **nested**.

In [32]:
nested = [empty, 10, 20.0, "Thirty", simple]

[PythonTutor](http://www.pythontutor.com/visualize.html#code=empty%20%3D%20%5B%5D%0Asimple%20%3D%20%5B40,%2050%5D%0Anested%20%3D%20%5Bempty,%2010,%2020.0,%20%22Thirty%22,%20simple%5D&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows how `nested` holds references to the `empty` and `simple` objects. Technically, it holds three more references to the `10`, `20.0`, and `"Thirty"` objects as well. However, to simplify the visualization, these three objects are shown right inside the `nested` object. That may be done because they are immutable and "flat" data types. In general, the $0$s and $1$s inside a `list` object in memory always constitute references to other objects only.

In [33]:
nested

[[], 10, 20.0, 'Thirty', [40, 50]]

Let's not forget that `nested` is an object on its own with an *identity* and *data type*.

In [34]:
id(nested)

140157873498184

In [35]:
type(nested)

list

Alternatively, we use the [list()](https://docs.python.org/3/library/functions.html#func-list) built-in to create a `list` object out of an iterable we pass to it as the argument.

For example, we can wrap the [range()](https://docs.python.org/3/library/functions.html#func-range) built-in with [list()](https://docs.python.org/3/library/functions.html#func-list): As described in [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#Containers-vs.-Iterables), `range` objects, like `range(1, 13)` below, are iterable and generate `int` objects "on the fly" (i.e., one by one). The [list()](https://docs.python.org/3/library/functions.html#func-list) around it acts like a `for`-loop and **materializes** twelve `int` objects in memory that then become the elements of the newly created `list` object. [PythonTutor](http://www.pythontutor.com/visualize.html#code=r%20%3D%20range%281,%2013%29%0Al%20%3D%20list%28range%281,%2013%29%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows this difference visually.

In [36]:
list(range(1, 13))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [37]:
isinstance(range(1, 13), abc.Iterable)

True

Beware of passing a `range` object over a "big" horizon as the argument to [list()](https://docs.python.org/3/library/functions.html#func-list) as that may lead to a `MemoryError` and the computer crashing.

In [38]:
list(range(999_999_999_999))

MemoryError: 

As another example, we create a `list` object from a `str` object, which is iterable, as well. Then, the individual characters become the elements of the new `list` object!

In [39]:
list("iterable")

['i', 't', 'e', 'r', 'a', 'b', 'l', 'e']

### Sequence Behaviors

`list` objects are *sequences*. To reiterate that, we briefly summarize the *four* behaviors of a sequence and provide some more `list`-specific details below:

- `Container`:
 - holds references to other objects in memory (with their own *identity* and *type*)
 - implements membership testing via the `in` operator
- `Iterable`:
 - supports being looped over
 - works with the `for` or `while` statements
- `Reversible`:
 - the elements come in a *predictable* order that we may traverse in a forward or backward fashion
 - works with the [reversed()](https://docs.python.org/3/library/functions.html#reversed) built-in
- `Sized`:
 - the number of elements is finite *and* known in advance
 - works with the built-in [len()](https://docs.python.org/3/library/functions.html#len) function

The "length" of `nested` is *five* because `empty` and `simple` count as *one* element each. In other words, `nested` holds five references to other objects, two of which are `list` objects.

In [40]:
len(nested)

5

With a `for`-loop, we can iterate over all elements in a *predictable* order, forward or backward. As `list` objects hold *references* to other *objects*, these have an *indentity* and may even be of *different* types; however, the latter observation is rarely, if ever, useful in practice.

In [41]:
for element in nested:
    print(element, id(element), type(element), sep="      \t")

[]      	140157882223304      	<class 'list'>
10      	93987402609984      	<class 'int'>
20.0      	140157882328912      	<class 'float'>
Thirty      	140157873509520      	<class 'str'>
[40, 50]      	140157873031176      	<class 'list'>


In [42]:
for element in reversed(nested):
    print(element, end="     ")

[40, 50]     Thirty     20.0     10     []     

The `in` operator checks if a given object is "contained" in a `list` object. It uses the `==` operator behind the scenes (i.e., *not* the `is` operator) conducting a **[linear search](https://en.wikipedia.org/wiki/Linear_search)**: So, Python implicitly loops over *all* elements and only stops prematurely if an element evaluates equal to the searched object. A linear search may, therefore, be relatively *slow* for big `list` objects.

In [43]:
10 in nested

True

`20` compares equal to the `20.0` in `nested`.

In [44]:
20 in nested

True

In [45]:
30 in nested

False

### Indexing

Because of the *predictable* order and the *finiteness*, each element in a sequence can be labeled with a unique *index*, an `int` object in the range $0 \leq \text{index} < \lvert \text{sequence} \rvert$.

Brackets, `[` and `]`, are the literal syntax for accessing individual elements of any sequence type. In this book, we also call them the *indexing operator* in this context.

In [46]:
nested[1]

10

The last index is one less than `len(nested)`, and Python raises an `IndexError` if we look up an index that is not in the range.

In [47]:
nested[5]

IndexError: list index out of range

Negative indices are used to count in reverse order from the end of a sequence, and brackets may be chained to access nested objects. So, to access the `50` inside `simple` via the `nested` object, we write `nested[-1][1]`.

In [48]:
nested[-1]

[40, 50]

In [49]:
nested[-1][1]

50

### Slicing

Slicing `list` objects works analogously to slicing `str` objects: We use the literal syntax with either one or two colons `:` inside the brackets `[]` to separate the *start*, *stop*, and *step* values. Slicing creates a *new* `list` object with the elements chosen from the original one.

For example, to obtain the three elements in the "middle" of `nested`, we slice from `1` (including) to `4` (excluding).

In [50]:
nested[1:4]

[10, 20.0, 'Thirty']

To obtain "every other" element, we slice from beginning to end, defaulting to `0` and `len(nested)` when omitted, in steps of `2`.

In [51]:
nested[::2]

[[], 20.0, [40, 50]]

The literal notation with the colons `:` is *syntactic sugar*. It saves us from using the [slice()](https://docs.python.org/3/library/functions.html#slice) built-in to create `slice` objects. [slice()](https://docs.python.org/3/library/functions.html#slice) takes *start*, *stop*, and *step* arguments in the same way as the familiar [range()](https://docs.python.org/3/library/functions.html#func-range), and the `slice` objects it creates are used just as *indexes* above.

In most cases, the literal notation is more convenient to use; however, with `slice` objects, we can give names to slices and reuse them across several sequences.

In [52]:
middle = slice(1, 4)

In [53]:
type(middle)

slice

In [54]:
nested[middle]

[10, 20.0, 'Thirty']

In [55]:
numbers[middle]

[11, 8, 5]

In [56]:
text[middle]

'ore'

`slice` objects come with three read-only attributes `start`, `stop`, and `step` on them.

In [57]:
middle.start

1

In [58]:
middle.stop

4

If not passed to [slice()](https://docs.python.org/3/library/functions.html#slice), these attributes default to `None`. That is why the cell below has no output.

In [59]:
middle.step

A good trick to know is taking a "full" slice: This copies *all* elements of a `list` object into a *new* `list` object.

In [60]:
nested_copy = nested[:]

In [61]:
nested_copy

[[], 10, 20.0, 'Thirty', [40, 50]]

At first glance, `nested` and `nested_copy` seem to cause no pain. For `list` objects, the comparison operator `==` goes over the elements in both operands in a pairwise fashion and checks if they all evaluate equal (cf., the "*List Comparison*" section below for more details).

We confirm that `nested` and `nested_copy` compare equal as could be expected but also that they are *different* objects.

In [62]:
nested == nested_copy

True

In [63]:
nested is nested_copy

False

However, as [PythonTutor](http://pythontutor.com/visualize.html#code=nested%20%3D%20%5B%5B%5D,%2010,%2020.0,%20%22Thirty%22,%20%5B40,%2050%5D%5D%0Anested_copy%20%3D%20nested%5B%3A%5D&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) reveals, only the *references* to the elements are copied, and not the objects in `nested` themselves! Because of that, `nested_copy` is a so-called **[shallow copy](https://en.wikipedia.org/wiki/Object_copying#Shallow_copy)** of `nested`.

We could also see this with the [id()](https://docs.python.org/3/library/functions.html#id) function: The respective first elements in both `nested` and `nested_copy` are the *same* object, namely `empty`.  So, we have three ways of accessing the *same* address in memory. Also, we say that `nested` and `nested_copy` partially share the *same* state.

In [64]:
nested[0] is nested_copy[0]

True

In [65]:
id(nested[0])

140157882223304

In [66]:
id(nested_copy[0])

140157882223304

In [67]:
id(empty)

140157882223304

Knowing this becomes critical if the elements in a `list` object are mutable objects (i.e., we can change them *in place*), and this is the case with `nested` and `nested_copy`, as we see in the next section on "*Mutability*".

As both the original `nested` object and its copy reference the *same* `list` objects in memory, any changes made to them are visible to both! Because of that, working with shallow copies can easily become confusing.

Instead of a shallow copy, we could also create a so-called **[deep copy](https://en.wikipedia.org/wiki/Object_copying#Deep_copy)** of `nested`: Then, the copying process recursively follows every reference in a nested data structure and creates copies of *every* object found.

To explicitly create shallow or deep copies, the [copy](https://docs.python.org/3/library/copy.html) module in the [standard library](https://docs.python.org/3/library/index.html) provides two functions, [copy()](https://docs.python.org/3/library/copy.html#copy.copy) and [deepcopy()](https://docs.python.org/3/library/copy.html#copy.deepcopy). We must always remember that slicing creates *shallow* copies only.

In [68]:
import copy

In [69]:
nested_deep_copy = copy.deepcopy(nested)

In [70]:
nested == nested_deep_copy

True

Now, the first elements of `nested` and `nested_deep_copy` are *different* objects, and [PythonTutor](http://pythontutor.com/visualize.html#code=import%20copy%0Anested%20%3D%20%5B%5B%5D,%2010,%2020.0,%20%22Thirty%22,%20%5B40,%2050%5D%5D%0Anested_deep_copy%20%3D%20copy.deepcopy%28nested%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows that there are *six* `list` objects in memory.

In [71]:
nested[0] is nested_deep_copy[0]

False

In [72]:
id(nested[0])

140157882223304

In [73]:
id(nested_deep_copy[0])

140157873029448

As this [StackOverflow question](https://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy) shows, understanding shallow and deep copies is a common source of confusion independent of the programming language.

### Mutability

In contrast to `str` objects, `list` objects are *mutable*: We may assign new elements to indices or slices and also remove elements. That changes the *references* in a `list` object. In general, if an object is *mutable*, we say that it may be changed *in place*.

In [74]:
nested[0] = 0

In [75]:
nested

[0, 10, 20.0, 'Thirty', [40, 50]]

When we re-assign a slice, we can even change the size of the `list` object.

In [76]:
nested[:4] = [100, 100, 100]  # assign three elements where there were four before

In [77]:
nested

[100, 100, 100, [40, 50]]

In [78]:
len(nested)

4

The `list` object's identity does *not* change. That is the main point behind mutable objects.

In [79]:
id(nested)

140157873498184

`nested_copy` is unchanged!

In [80]:
nested_copy

[[], 10, 20.0, 'Thirty', [40, 50]]

Let's change the nested `[40, 50]` via `nested_copy` into `[1, 2, 3]` by replacing all its elements.

In [81]:
nested_copy[-1][:] = [1, 2, 3]

In [82]:
nested_copy

[[], 10, 20.0, 'Thirty', [1, 2, 3]]

That has a surprising side effect on `nested`.

In [83]:
nested

[100, 100, 100, [1, 2, 3]]

That is precisely the confusion we talked about above when we said that `nested_copy` is a *shallow* copy of `nested`. [PythonTutor](http://pythontutor.com/visualize.html#code=nested%20%3D%20%5B%5B%5D,%2010,%2020.0,%20%22Thirty%22,%20%5B40,%2050%5D%5D%0Anested_copy%20%3D%20nested%5B%3A%5D%0Anested%5B%3A4%5D%20%3D%20%5B100,%20100,%20100%5D%0Anested_copy%5B-1%5D%5B%3A%5D%20%3D%20%5B1,%202,%203%5D&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows how both reference the *same* nested `list` object that is changed *in place* from `[40, 50]` into `[1, 2, 3]`.

Lastly, we use the `del` statement to remove an element.

In [84]:
del nested[-1]

In [85]:
nested

[100, 100, 100]

The `del` statement also works for slices. Here, we remove all references `nested` holds.

In [86]:
del nested[:]

In [87]:
nested

[]

Mutability for sequences is formalized by the `MutableSequence` ABC in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module.

So, we can als "ask" Python if `nested` is mutable.

In [88]:
isinstance(nested, abc.MutableSequence)

True

### List Methods

The `list` type is an essential data structure in any real-world Python application, and many typical `list`-related algorithms from computer science theory are already built into it at the C level (cf., the [documentation](https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types) or the [tutorial](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) for a full overview; unfortunately, not all methods have direct links). So, understanding and applying the built-in methods of the `list` type not only speeds up the development process but also makes programs significantly faster.

In contrast to the `str` type's methods in [Chapter 6](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/06_text.ipynb#String-Methods) (e.g., [upper()](https://docs.python.org/3/library/stdtypes.html#str.upper) or [lower()](https://docs.python.org/3/library/stdtypes.html#str.lower)), the `list` type's methods that mutate an object do so *in place*. That means they *never* create *new* `list` objects and return `None` to indicate that. So, we must *never* assign the return value of `list` methods to the variable holding the list!

Let's look at the following `names` example.

In [89]:
names = ["Carl", "Peter"]

To add an object to the end of `names`, we use the `append()` method. The code cell shows no output indicating that `None` must be the return value.

In [90]:
names.append("Eckardt")

In [91]:
names

['Carl', 'Peter', 'Eckardt']

With the `extend()` method, we may also append multiple elements provided by an iterable. Here, the iterable is a `list` object itself holding two `str` objects.

In [92]:
names.extend(["Karl", "Oliver"])

In [93]:
names

['Carl', 'Peter', 'Eckardt', 'Karl', 'Oliver']

Similar to `append()`, we may add a new element at an arbitrary position with the `insert()` method. `insert()` takes two arguments, an *index* and the element to be inserted.

In [94]:
names.insert(1, "Berthold")

In [95]:
names

['Carl', 'Berthold', 'Peter', 'Eckardt', 'Karl', 'Oliver']

`list` objects may be sorted *in place* with the [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) method. That is different from the built-in [sorted()](https://docs.python.org/3/library/functions.html#sorted) function that takes any *finite* and *iterable* object and returns a *new* `list` object with the iterable's elements sorted!

In [96]:
sorted(names)

['Berthold', 'Carl', 'Eckardt', 'Karl', 'Oliver', 'Peter']

As the previous code cell created a *new* `list` object, `names` is still unsorted.

In [97]:
names

['Carl', 'Berthold', 'Peter', 'Eckardt', 'Karl', 'Oliver']

Let's sort the elements in `names` instead.

In [98]:
names.sort()

In [99]:
names

['Berthold', 'Carl', 'Eckardt', 'Karl', 'Oliver', 'Peter']

To sort in reverse order, we pass a keyword-only `reverse=True` argument to either the [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) method or the [sorted()](https://docs.python.org/3/library/functions.html#sorted) function.

In [100]:
names.sort(reverse=True)

In [101]:
names

['Peter', 'Oliver', 'Karl', 'Eckardt', 'Carl', 'Berthold']

The [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) method and the [sorted()](https://docs.python.org/3/library/functions.html#sorted) function sort the elements in `names` in alphabetical order, forward or backward. However, that does *not* hold in general.

We mention above that `list` objects may contain objects of *any* type and even of *mixed* types. Because of that, the sorting is **[delegated](https://en.wikipedia.org/wiki/Delegation_(object-oriented_programming))** to the elements in a `list` object. In a way, Python "asks" the elements in a `list` object to sort themselves. As `names` contains only `str` objects, they are sorted according the the comparison rules explained in [Chapter 6](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/06_text.ipynb#String-Comparison).

To customize the sorting, we pass a keyword-only `key` argument to [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) or [sorted()](https://docs.python.org/3/library/functions.html#sorted), which must be a `function` object accepting *one* positional argument. Then, the elements in the `list` object are passed to that one by one, and the return values are used as the **sort keys**. The `key` argument is also a popular use case for `lambda` expressions.

For example, to sort `names` not by alphabet but by the names' lengths, we pass in a reference to the built-in [len()](https://docs.python.org/3/library/functions.html#len) function as `key=len`. Note that there are *no* parentheses after `len`!

In [102]:
names.sort(key=len)

If two names have the same length, their relative order is kept as is. That is why `"Karl"` comes before `"Carl" ` below. A [sorting algorithm](https://en.wikipedia.org/wiki/Sorting_algorithm) with that property is called **[stable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability)**.

Sorting is an important topic in programming, and we refer to the official [HOWTO](https://docs.python.org/3/howto/sorting.html) for a more comprehensive introduction.

In [103]:
names

['Karl', 'Carl', 'Peter', 'Oliver', 'Eckardt', 'Berthold']

`sort(reverse=True)` is different from the `reverse()` method. Whereas the former applies some sorting rule in reverse order, the latter simply reverses the elements in a `list` object.

In [104]:
names.reverse()

In [105]:
names

['Berthold', 'Eckardt', 'Oliver', 'Peter', 'Carl', 'Karl']

The `pop()` method removes the *last* element from a `list` object *and* returns it. Below we **capture** the `removed` element to show that the return value is not `None` as with all the methods introduced so far.

In [106]:
removed = names.pop()

In [107]:
removed

'Karl'

In [108]:
names

['Berthold', 'Eckardt', 'Oliver', 'Peter', 'Carl']

`pop()` takes an optional *index* argument and removes that instead.

So, to remove the second element, `"Eckhardt"`, from `names`, we write this.

In [109]:
removed = names.pop(1)

In [110]:
removed

'Eckardt'

In [111]:
names

['Berthold', 'Oliver', 'Peter', 'Carl']

Instead of removing an element by its index, we can also remove it by its value with the `remove()` method. Behind the scenes, Python then compares the object to be removed, `"Peter"` in the example, sequentially to each element with the `==` operator and removes the *first* one that evaluates equal to it. `remove()` does *not* return the removed element.

In [112]:
names.remove("Peter")

In [113]:
names

['Berthold', 'Oliver', 'Carl']

Also, `remove()` raises a `ValueError` if the value is not found.

In [114]:
names.remove("Peter")

ValueError: list.remove(x): x not in list

`list` objects implement an `index()` method that returns the position of the first element that compares equal to its argument. It fails *loudly* with a `ValueError` if no element compares equal.

In [115]:
names

['Berthold', 'Oliver', 'Carl']

In [116]:
names.index("Oliver")

1

In [117]:
names.index("Karl")

ValueError: 'Karl' is not in list

The `count()` method returns the number of elements that compare equal to its argument.

In [118]:
names.count("Carl")

1

In [119]:
names.count("Karl")

0

Two more methods, `copy()` and `clear()`, are *syntactic sugar* and replace working with slices.

`copy()` creates a *shallow* copy. So, `names.copy()` below does the same as taking a full slice with `names[:]`, and the caveats from above apply, too.

In [120]:
names_copy = names.copy()

In [121]:
names_copy

['Berthold', 'Oliver', 'Carl']

`clear()` removes all references from a `list` object. So, `names_copy.clear()` is the same as `del names_copy[:]`.

In [122]:
names_copy.clear()

In [123]:
names_copy

[]

Many methods introduced in this section are mentioned in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module's documentation as well: While the `index()` and `count()` methods come with any data type that is a `Sequence`, the `append()`, `extend()`, `insert()`, `reverse()`, `pop()`, and `remove()` methods are part of any `MutableSequence` type. The `sort()`, `copy()`, and `clear()` methods are `list`-specific.

So, being a sequence does not only imply the four *behaviors* specified above, but also means that a data type comes with certain standardized methods.

### List Operations

As with `str` objects, the `+` and `*` operators are overloaded for concatenation and always return a *new* `list` object. The references in this newly created `list` object reference the *same* objects as the two original `list` objects. So, the same caveat as with *shallow* copies from above applies!

In [124]:
names

['Berthold', 'Oliver', 'Carl']

In [125]:
more_names = ["Diedrich", "Yves"]

In [126]:
names + more_names

['Berthold', 'Oliver', 'Carl', 'Diedrich', 'Yves']

In [127]:
2 * names

['Berthold', 'Oliver', 'Carl', 'Berthold', 'Oliver', 'Carl']

In [128]:
more_names * 3

['Diedrich', 'Yves', 'Diedrich', 'Yves', 'Diedrich', 'Yves']

Besides being an operator, the `*` symbol has a second syntactical use, as explained in [PEP 3132](https://www.python.org/dev/peps/pep-3132/) and [PEP 448](https://www.python.org/dev/peps/pep-0448/): It implements what is called **iterable unpacking**. It is *not* an operator syntactically but a notation that Python reads as a literal.

In the example, Python interprets the expression as if the elements of the iterable `names` were placed between `"Achim"` and `"Xavier"` one by one. So, we do not obtain a nested but a *flat* list.

In [129]:
["Achim", *names, "Xavier"]

['Achim', 'Berthold', 'Oliver', 'Carl', 'Xavier']

Effectively, Python reads that as if we wrote the following.

In [130]:
["Achim", names[0], names[1], names[2], "Xavier"]

['Achim', 'Berthold', 'Oliver', 'Carl', 'Xavier']

#### List Comparison

The relational operators also work with `list` objects; yet another example of operator overloading.

Comparison is made in a pairwise fashion until the first pair of elements does not evaluate equal or one of the `list` objects ends. The exact comparison rules depend on the elements and not the `list` objects. As with [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) or [sorted()](https://docs.python.org/3/library/functions.html#sorted) above, comparison is *delegated* to the objects to be compared, and Python "asks" the elements in the two `list` objects to compare themselves. Usually, all elements are of the *same* type, and comparison is straightforward.

In [131]:
names

['Berthold', 'Oliver', 'Carl']

In [132]:
names == ["Berthold", "Oliver", "Carl"]

True

In [133]:
names != ["Berthold", "Oliver", "Karl"]

True

In [134]:
names < ["Berthold", "Oliver", "Karl"]

True

In [135]:
["Achim", "Oliver", "Carl"] < names

True

If two `list` objects have a different number of elements and all overlapping elements compare equal, the shorter `list` object is considered "smaller." That rule is a common cause for *semantic* errors in a program.

In [136]:
["Berthold", "Oliver"] < names

True

In [137]:
names < ["Berthold", "Oliver", "Carl", "Xavier"]

True

### Modifiers vs. Pure Functions

As `list` objects are mutable, the caller of a function can see the changes made to a `list` object passed to the function as an argument. That is often a surprising *side effect* and should be avoided.

As an example, consider the `add_xyz()` function.

In [138]:
letters = ["a", "b", "c"]

In [139]:
def add_xyz(arg):
    """Append letters to a list."""
    arg.extend(["x", "y", "z"])
    return arg

While this function is being executed, two variables, namely `letters` in the global scope and `arg` inside the function's local scope, reference the *same* `list` object in memory. Furthermore, the passed in `arg` is also the return value.

So, after the function call, `letters_with_xyz` and `letters` are **aliases** as well, referencing the *same* object.

In [140]:
letters_with_xyz = add_xyz(letters)

In [141]:
letters_with_xyz

['a', 'b', 'c', 'x', 'y', 'z']

In [142]:
letters

['a', 'b', 'c', 'x', 'y', 'z']

A better practice is to first create a copy of `arg` within the function that is then modified and returned. If we are sure that `arg` contains immutable elements only, we get away with a shallow copy. The downside of this approach is the higher amount of memory necessary.

The revised `add_xyz()` function below is more natural to reason about as it does *not* modify the passed in `arg` internally. This approach is following the **[functional programming](https://en.wikipedia.org/wiki/Functional_programming)** paradigm that is going through a "renaissance" currently. Two essential characteristics of functional programming are that a function *never* changes its inputs and *always* returns the same output given the same inputs.

For a beginner, it is probably better to stick to this idea and not change any arguments as the original `add_xyz()` above. However, functions that modify and return the argument passed in are an important aspect of object-oriented programming, as explained in Chapter 9.

In [143]:
letters = ["a", "b", "c"]

In [144]:
def add_xyz(arg):
    """Create a new list from an existing one."""
    new_arg = arg[:]  # a shallow copy is good enough here
    new_arg.extend(["x", "y", "z"])
    return new_arg

In [145]:
letters_with_xyz = add_xyz(letters)

In [146]:
letters_with_xyz

['a', 'b', 'c', 'x', 'y', 'z']

In [147]:
letters

['a', 'b', 'c']

If we want to modify the argument passed in, it is best to return `None` and not `arg`, as does the final version of `add_xyz()` below. Then, the user of our function cannot accidentally create two aliases to the same object. That is also why the list methods above all return `None`.

In [148]:
letters = ["a", "b", "c"]

In [149]:
def add_xyz(arg):
    """Append letters to a list."""
    arg.extend(["x", "y", "z"])
    return  # = None

In [150]:
add_xyz(letters)

In [151]:
letters

['a', 'b', 'c', 'x', 'y', 'z']

If we call `add_xyz()` with `letters` as the argument again, we end up with an even longer `list` object.

In [152]:
add_xyz(letters)

In [153]:
letters

['a', 'b', 'c', 'x', 'y', 'z', 'x', 'y', 'z']

Functions that only work on the argument passed in are called **modifiers**. Their primary purpose is to change the **state** of the argument. On the contrary, functions that have *no* side effects on the arguments are said to be **pure**.

## The `tuple` Type

To create a `tuple` object, we can use the same literal notation as for `list` objects *without* the brackets and list all elements.

In [154]:
numbers = 7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4

In [155]:
numbers

(7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

However, to be clearer, many Pythonistas write out the optional parentheses `(` and `)`.

In [156]:
numbers = (7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

In [157]:
numbers

(7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

As before, `numbers` is an object on its own.

In [158]:
id(numbers)

140157873009144

In [159]:
type(numbers)

tuple

While we could use empty parentheses `()` to create an empty `tuple` object ...

In [160]:
empty_tuple = ()

In [161]:
empty_tuple

()

In [162]:
type(empty_tuple)

tuple

... we must use a *trailing comma* to create a `tuple` object holding one element. If we forget the comma, the parentheses are interpreted as the grouping operator and effectively useless!

In [163]:
one_tuple = (1,)  # we could ommit the parentheses but not the comma

In [164]:
one_tuple

(1,)

In [165]:
type(one_tuple)

tuple

In [166]:
no_tuple = (1)

In [167]:
no_tuple

1

In [168]:
type(no_tuple)

int

Alternatively, we may use the [tuple()](https://docs.python.org/3/library/functions.html#func-tuple) built-in that takes any iterable as its argument and creates a new `tuple` from its elements.

In [169]:
tuple([1])

(1,)

In [170]:
tuple("iterable")

('i', 't', 'e', 'r', 'a', 'b', 'l', 'e')

### Tuples are like "Immutable Lists"

Most operations involving `tuple` objects work in the same way as with `list` objects. The main difference is that `tuple` objects are *immutable*. So, if our program does not depend on mutability, we may and should use `tuple` and not `list` objects to model sequential data. That way, we avoid the pitfalls seen above.

`tuple` objects are *sequences* exhibiting the familiar *four* behaviors.

In [171]:
isinstance(numbers, abc.Sequence)

True

 So, `numbers` holds a *finite* number of elements ...

In [172]:
len(numbers)

12

... that we can obtain individually by looping over it in a predictable *forward* or *reverse* order.

In [173]:
for number in numbers:
    print(number, end="   ")

7   11   8   5   3   12   2   6   9   10   1   4   

In [174]:
for number in reversed(numbers):
    print(number, end="   ")

4   1   10   9   6   2   12   3   5   8   11   7   

To check if a given object is *contained* in `numbers`, we use the `in` operator and conduct a linear search.

In [175]:
0 in numbers

False

In [176]:
1 in numbers

True

In [177]:
1.0 in numbers  # in relies on == behind the scenes

True

We may index and slice with the `[]` operator. The latter returns *new* `tuple` objects.

In [178]:
numbers[0]

7

In [179]:
numbers[-1]

4

In [180]:
numbers[6:]

(2, 6, 9, 10, 1, 4)

Index assignment does *not* work as tuples are *immutable* and results in a `TypeError`.

In [181]:
numbers[-1] = 99

TypeError: 'tuple' object does not support item assignment

We can verify the immutability with the `MutableSequence` ABC from the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module: [isinstance()](https://docs.python.org/3/library/functions.html#isinstance) returns `False`. So, a data type that is a `Sequence` may be mutable or not. If it is a `MutableSequence`, it is mutable. If it is *not* a `MutableSequence`, it is *immutable*. There is *no* `ImmutableSequence` ABC.

In [182]:
isinstance(numbers, abc.MutableSequence)

False

The `+` and `*` operators work with `tuple` objects as well. However, we should *not* do that as the whole point of immutability is to *not* mutate an object.

So, instead of writing something like below, we should use a `list` object and call its `append()` method.

In [183]:
numbers + (99,) 

(7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4, 99)

In [184]:
2 * numbers

(7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4, 7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

Being immutable, `tuple` objects only provide the `count()` and `index()` methods of `Sequence` types. The `append()`, `extend()`, `insert()`, `reverse()`, `pop()`, and `remove()` methods of `MutableSequence` types are *not* available. The same holds for the `list`-specific methods `sort()`, `copy()`, and `clear()`.

In [185]:
numbers.count(0)

0

In [186]:
numbers.index(1)

10

The relational operators work in the *same* way as for `list` objects.

In [187]:
numbers

(7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

In [188]:
numbers == (7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

True

In [189]:
numbers != (99, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

True

In [190]:
numbers < (99, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4)

True

In [191]:
(0, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4) < numbers

True

While `tuple` objects are immutable, this only relates to the references they hold. If a `tuple` object contains mutable objects, the entire nested structure is *not* immutable as a whole.

Consider the following stylized example `not_immutable`: It contains *three* elements, `1`, `[2, ..., 11]`, and `12`, and the elements of the nested `list` object may be changed. While it is not practical to mix data types in a `tuple` object that is used as an "immutable list," we want to make the point that the mere usage of the `tuple` type does *not* guarantee a nested object to be immutable as a whole.

In [192]:
not_immutable = (1, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 12)

In [193]:
not_immutable

(1, [2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 12)

In [194]:
not_immutable[1][:] = [99, 99, 99]

In [195]:
not_immutable

(1, [99, 99, 99], 12)

### Packing & Unpacking

In the "*List Operations*" section above, the `*` symbol **unpacks** the elements of a `list` object into another one. This idea of *iterable unpacking* is built into Python at various places, even *without* the `*` symbol.

For example, we may write variables on the left-hand side of a `=` statement in a `tuple` style. Then,  any *finite* iterable on the right-hand side is unpacked. So, `numbers` is unpacked into *twelve* variables below.

In [196]:
n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12 = numbers

In [197]:
n1

7

In [198]:
n2

11

In [199]:
n3

8

Having to type twelve variables on the left is already tedious. Furthermore, if the iterable on the right yields a number of elements *different* from the number of variables, we get a `ValueError`.

In [200]:
n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11 = numbers

ValueError: too many values to unpack (expected 11)

In [201]:
n1, n2, n3, n4, n5, n6, n7, n8, n9, n10, n11, n12, n13 = numbers

ValueError: not enough values to unpack (expected 13, got 12)

So, to make iterable unpacking useful, we prepend the `*` symbol to *one* of the variables on the left: That variable then becomes a `list` object holding the elements not captured by the other variables. We say that the excess elements from the iterable are **packed** into this variable.

For example, let's get the `first` and `last` element of `numbers` and collect the rest in `middle`.

In [202]:
first, *middle, last = numbers

In [203]:
first

7

In [204]:
middle

[11, 8, 5, 3, 12, 2, 6, 9, 10, 1]

In [205]:
last

4

If we do not need the `middle` elements, we go with the underscore `_` convention and "throw" them away.

In [206]:
first, *_, last = numbers

In [207]:
first

7

In [208]:
last

4

We already used unpacking before this section without knowing it. Whenever we write a `for`-loop over the [zip()](https://docs.python.org/3/library/functions.html#zip) built-in, that generates a new `tuple` object in each iteration, which we unpack by listing several loop variables.

So, the `name, position` acts like a left-hand side of an `=` statement and unpacks the `tuple` objects generated from "zipping" the `names` list and the `positions` tuple together.

In [209]:
positions = ("goalkeeper", "defender", "midfielder", "striker", "coach")

In [210]:
for name, position in zip(names, positions):
    print(name, "is a", position)

Berthold is a goalkeeper
Oliver is a defender
Carl is a midfielder


Without unpacking, [zip()](https://docs.python.org/3/library/functions.html#zip) generates a series of `tuple` objects.

In [211]:
for pair in zip(names, positions):
    print(type(pair), pair, sep="   ")

<class 'tuple'>   ('Berthold', 'goalkeeper')
<class 'tuple'>   ('Oliver', 'defender')
<class 'tuple'>   ('Carl', 'midfielder')


Unpacking also works for nested objects. Below, we wrap [zip()](https://docs.python.org/3/library/functions.html#zip) with the [enumerate()](https://docs.python.org/3/library/functions.html#enumerate) built-in to have an index variable `i` inside the `for`-loop. In each iteration, a `tuple` object consisting of `i` and another `tuple` object is created. The inner one then holds the `name` and `position`.

In [212]:
for i, (name, position) in enumerate(zip(names, positions)):
    print(i, "->", name, "is a", position)

0 -> Berthold is a goalkeeper
1 -> Oliver is a defender
2 -> Carl is a midfielder


#### Swapping Variables

A popular use case of unpacking is **swapping** two variables.

Consider `a` and `b` below.

In [213]:
a = 0
b = 1

Without unpacking, we must use a temporary variable `temp` to swap `a` and `b`.

In [214]:
temp = a
a = b
b = temp

In [215]:
a, b

(1, 0)

With unpacking, the solution is more elegant, and also a bit faster as well. *All* expressions on the right-hand side are evaluated *before* any assignment takes place.

In [216]:
a = 0
b = 1

In [217]:
a, b = b, a

In [218]:
a, b

(1, 0)

#### Example: [Fibonacci Numbers](https://en.wikipedia.org/wiki/Fibonacci_number) (revisited)

Unpacking allows us to rewrite the iterative `fibonacci()` function from [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#"Hard-at-first-Glance"-Example:-Fibonacci-Numbers-%28revisited%29) in a concise way, now also supporting *goose typing* with the [numbers](https://docs.python.org/3/library/numbers.html) module from the [standard library](https://docs.python.org/3/library/index.html).

In [219]:
import numbers

In [220]:
def fibonacci(i):
    """Calculate the ith Fibonacci number.

    Args:
        i (int): index of the Fibonacci number to calculate

    Returns:
        ith_fibonacci (int)

    Raises:
        TypeError: if i is not an integer or not integer-like
        ValueError: if i is not positive
    """
    if not isinstance(i, numbers.Integral):
        if isinstance(i, numbers.Real):
            if i != int(i):
                raise TypeError("i is not an integer-like value; it has decimals")
            i = int(i)
        else:
            raise TypeError("i must be an integer")
    if i < 0:
        raise ValueError("i must be non-negative")

    a, b = 0, 1

    for _ in range(i - 1):
        a, b = b, a + b

    return b

In [221]:
fibonacci(12)

144

Because of the *goose typing*, we may pass `float` objects to `fibonacci()` as long as they contain no decimals.

In [222]:
fibonacci(12.0)

144

In [223]:
fibonacci(12.3)

TypeError: i is not an integer-like value; it has decimals

#### Function Definitions & Calls

The concepts of packing and unpacking are also helpful when writing and using functions.

For example, let's look at the `product()` function below. Its implementation suggests that `args` must be a sequence type. Otherwise, it would not make sense to index into it with `[0]` or take a slice with `[1:]`. In line with the function's name, the `for`-loop multiplies all elements of the `args` sequence. So, what does the `*` do in the header line, and what is the exact data type of `args`?

The `*` is again *not* an operator in this context but a special syntax that makes Python *pack* all *positional* arguments passed to `product()` into a single `tuple` object called `args`.

In [224]:
def product(*args):
    """Multiply all arguments."""
    result = args[0]

    for arg in args[1:]:
        result *= arg

    return result

So, we can pass an *arbitrary* (i.e., also none) number of *positional* arguments to `product()`.

The product of just one number is the number itself.

In [225]:
product(42)

42

Passing in several numbers works as expected.

In [226]:
product(2, 5, 10)

100

However, this implementation of `product()` needs *at least* one argument passed in due to the expression `args[0]` used internally. Otherwise, we see a *runtime* error, namely an `IndexError`. We emphasize that this error is *not* caused in the header line.

In [227]:
product()

IndexError: tuple index out of range

Another downside of this implementation is that we can easily generate *semantic* errors: For example, if we pass in an iterable object like the `one_hundred` list, *no* exception is raised. However, the return value is also not a numeric object as we expect. The reason for this is that during the function call, `args` becomes a `tuple` object holding *one* element, which is `one_hundred`, a `list` object. So, we created a nested structure by accident.

In [228]:
one_hundred = [2, 5, 10]

In [229]:
product(one_hundred)

[2, 5, 10]

This error does not occur if we unpack `one_hundred` upon passing it as the argument.

In [230]:
product(*one_hundred)

100

That is the equivalent of writing out the following tedious expression. Yet, that does *not* scale for iterables with many elements in them.

In [231]:
product(one_hundred[0], one_hundred[1], one_hundred[2])

100

In the "*Packing & Unpacking with Functions*" [exercise](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/07_sequences_review_and_exercises.ipynb#Packing-&-Unpacking-with-Functions) at the end of this chapter, we look at `product()` in more detail.

While we needed to unpack `one_hundred` above to avoid the semantic error, unpacking an argument in a function call may also be a convenience in general.

For example, to print the elements of `one_hundred` in one line, we need to use a `for` statement, until now. With unpacking, we get away *without* a loop.

In [232]:
print(one_hundred)  # prints the tuple; we do not want that

[2, 5, 10]


In [233]:
for number in one_hundred:
    print(number, end=" ")

2 5 10 

In [234]:
print(*one_hundred)  # replaces the for-loop

2 5 10


### The `namedtuple` Type

Above, we proposed the idea that `tuple` objects are like "immutable lists." Often, however, we use `tuple` objects to represent a **record** of related **fields**. Then, each element has a *semantic* meaning (i.e., a descriptive name).

As an example, think of a spreadsheet with information on students in a course. Each row represents a record and holds all the data associated with an individual student. The columns (e.g., matriculation number, first name, last name) are the fields that may come as *different* data types (e.g., `int` for the matriculation number, `str` for the names).

A simple way of modeling a single student is as a `tuple` object, for example, `(123456, "John", "Doe")`. A disadvantage of this approach is that we must remember the order and meaning of the elements/fields in the `tuple` object.

An example from a different domain is the representation of $(x, y)$-points in the $x$-$y$-plane. Again, we could use a `tuple` object like `current_position` below to model the point $(4, 2)$.

In [235]:
current_position = (4, 2)

We implicitly assume that the first element represents the $x$ and the second the $y$ coordinate. While that follows intuitively from convention in math, we should at least add comments somewhere in the code to document this assumption.

A better way is to create a *custom* data type. While that is covered in depth in Chapter 9, the [collections](https://docs.python.org/3/library/collections.html) module in the [standard library](https://docs.python.org/3/library/index.html) provides a [namedtuple()](https://docs.python.org/3/library/collections.html#collections.namedtuple) **factory function** that creates "simple" custom data types on top of the standard `tuple` type.

In [236]:
from collections import namedtuple

[namedtuple()](https://docs.python.org/3/library/collections.html#collections.namedtuple) takes two arguments. The first argument is the name of the data type. That could be different from the variable `Point` we use to refer to the new type, but in most cases it is best to keep them in sync. The second argument is a sequence with the field names as `str` objects. The names' order corresponds to the one assumed in `current_position`.

In [237]:
Point = namedtuple("Point", ["x", "y"])

The `Point` object is a so-called **class**. That is what it means if an object is of type `type`. It can be used as a **factory** to create *new* `tuple`-like objects of type `Point`.

In [238]:
id(Point)  # classes are objects as well

140157466523464

In [239]:
type(Point)

type

The value of `Point` is just itself in a *literal notation*.

In [240]:
Point

__main__.Point

We write `Point(4, 2)` to create a *new* object of type `Point`.

In [241]:
current_position = Point(4, 2)

Now, `current_position` has a somewhat nicer representation. In particular, the coordinates are named `x` and `y`.

In [242]:
current_position

Point(x=4, y=2)

It is *not* a `tuple` any more but an object of type `Point`.

In [243]:
id(current_position)

140157872590424

In [244]:
type(current_position)

__main__.Point

We use the dot operator `.` to access the defined attributes.

In [245]:
current_position.x

4

In [246]:
current_position.y

2

As before, we get an `AttributeError` if we try to access an undefined attribute.

In [247]:
current_position.z

AttributeError: 'Point' object has no attribute 'z'

`current_position` continues to work like a `tuple` object! That is why we can use `namedtuple` as a replacement for `tuple`. The underlying implementations exhibit the *same* computational efficiencies and memory usages.

For example, we can index into or loop over `current_position` as it is still a sequence.

In [248]:
isinstance(current_position, abc.Sequence)

True

In [249]:
current_position[0]

4

In [250]:
current_position[1]

2

In [251]:
for number in current_position:
    print(number)

4
2


In [252]:
for number in reversed(current_position):
    print(number)

2
4


## The Map-Filter-Reduce Paradigm

Whenever we process sequential data, most tasks can be classified into one of the three categories **map**, **filter**, or **reduce**. This paradigm has caught attention in recent years as it enables **[parallel computing](https://en.wikipedia.org/wiki/Parallel_computing)**, and this gets important when dealing with big amounts of data.

Let's look at a simple example.

In [253]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

### Mapping

**Mapping** refers to the idea of applying a transformation to every element in a sequence.

For example, let's square each element in `numbers` and add `1` to it. In essence, we apply the transformation $y := x^2 + 1$ expressed as the `transform()` function below.

In [254]:
def transform(element):
    """Map elements to their squares plus 1."""
    return (element ** 2) + 1

With the syntax we know so far, we revert to a `for`-loop that iteratively appends the transformed elements to the initially empty `transformed_numbers` list.

In [255]:
transformed_numbers = []

for old in numbers:
    new = transform(old)
    transformed_numbers.append(new)

In [256]:
transformed_numbers

[50, 122, 65, 26, 10, 145, 5, 37, 82, 101, 2, 17]

As this kind of data processing is so common, Python provides the [map()](https://docs.python.org/3/library/functions.html#map) built-in. In its simplest usage form, it takes two arguments: A transformation function that takes one positional argument and an iterable.

We call [map()](https://docs.python.org/3/library/functions.html#map) with the `transform()` function and the `numbers` list as the arguments and store the result in the variable `transformer` to inspect it.

In [257]:
transformer = map(transform, numbers)

We might expect to get back a materialized sequence (i.e., all elements exist in memory), and a `list` object would feel the most natural because of the type of the `numbers` argument. However, `transformer` is an object of type `map`.

In [258]:
transformer

In [259]:
type(transformer)

map

Like `range` objects, `map` objects generate a series of objects "on the fly" (i.e., one by one), and we use the built-in [next()](https://docs.python.org/3/library/functions.html#next) function to obtain the next object in line. So, we should think of a `map` object as a "rule" stored in memory that only knows how to calculate the next object of possibly *infinitely* many.

It is essential to understand that by creating a `map` object with the [map()](https://docs.python.org/3/library/functions.html#map) built-in, nothing happens in memory except the creation of the `map` object. In particular, no second `list` object derived from `numbers` is created. Also, we may view `range` objects as a special case of `map` objects: They are constrained to generating `int` objects only, and the *iterable* argument is replaced with *start*, *stop*, and *step* arguments.

In [260]:
next(transformer)

50

In [261]:
next(transformer)

122

In [262]:
next(transformer)

65

If we are sure that a `map` object generates a *finite* number of elements, we may materialize them into a `list` object with the [list()](https://docs.python.org/3/library/functions.html#func-list) built-in. In the example, this is the case as `transformer` is derived from a *finite* `list` object.

In summary, instead of creating an empty list first and appending it in a `for`-loop as above, we write the following one-liner and obtain an equal `transformed_numbers` list.

In [263]:
transformed_numbers = list(map(transform, numbers))

In [264]:
transformed_numbers

[50, 122, 65, 26, 10, 145, 5, 37, 82, 101, 2, 17]

### Filtering

**Filtering** refers to the idea of creating a subset of a sequence with a **boolean filter** function that indicates if an element should be kept or not.

In the example, let's only keep the even elements in `numbers`. The `is_even()` function implements that as a filter.

In [265]:
def is_even(element):
    """Filter out odd numbers."""
    if element % 2 == 0:
        return True
    return False

As before, we must revert to a `for`-loop that appends the elements to be kept iteratively to an initially empty `even_numbers` list.

In [266]:
even_numbers = []

for number in transformed_numbers:
    if is_even(number):
        even_numbers.append(number)

In [267]:
even_numbers

[50, 122, 26, 10, 82, 2]

As filtering is also a common task, we use the [filter()](https://docs.python.org/3/library/functions.html#filter) built-in that returns an object of type `filter` stored in the `evens` variable.

In [268]:
evens = filter(is_even, transformed_numbers)

In [269]:
evens

In [270]:
type(evens)

filter

`evens` works like `transformer` above, and we use the built-in [next()](https://docs.python.org/3/library/functions.html#next) function to obtain the even numbers one by one. So, the "next" element in line is simply the next even `int` object the `filter` object encounters.

In [271]:
transformed_numbers  # for quick reference

[50, 122, 65, 26, 10, 145, 5, 37, 82, 101, 2, 17]

In [272]:
next(evens)

50

In [273]:
next(evens)

122

In [274]:
next(evens)

26

As above, we must explicitly create a materialized `list` object with the [list()](https://docs.python.org/3/library/functions.html#func-list) built-in.

In [275]:
list(filter(is_even, transformed_numbers))

[50, 122, 26, 10, 82, 2]

We may also chain mappings and filters based on the original `numbers` list.

In [276]:
list(filter(is_even, map(transform, numbers)))

[50, 122, 26, 10, 82, 2]

Using the [map()](https://docs.python.org/3/library/functions.html#map) and [filter()](https://docs.python.org/3/library/functions.html#filter) built-ins, we can quickly switch the order: Filter first and then transform the remaining elements. This variant equals the "*A simple Filter*" example from [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#Example:-A-simple-Filter). On the contrary, code with `for`-loops and `if` statements is more tedious to adapt. Additionally, `map` and `filter` objects are optimized at the C level and, therefore, a lot faster as well.

In [277]:
list(map(transform, filter(is_even, numbers)))

[65, 145, 5, 37, 101, 17]

### Reducing

Lastly, **reducing** sequential data means to summarize the elements into a single statistic.

A simple example is the built-in [sum()](https://docs.python.org/3/library/functions.html#sum) function.

In [278]:
sum(map(transform, filter(is_even, numbers)))

370

Other straightforward examples are the built-in [min()](https://docs.python.org/3/library/functions.html#min) or [max()](https://docs.python.org/3/library/functions.html#max) functions.

In [279]:
min(map(transform, filter(is_even, numbers)))

5

In [280]:
max(map(transform, filter(is_even, numbers)))

145

[sum()](https://docs.python.org/3/library/functions.html#sum), [min()](https://docs.python.org/3/library/functions.html#min), and [max()](https://docs.python.org/3/library/functions.html#max) can be regarded as special cases.

The generic way of reducing a sequence is to apply a function of *two* arguments on a rolling horizon: Its first argument is the reduction of the elements processed so far, and the second the next element to be reduced.

For illustration, let's replicate [sum()](https://docs.python.org/3/library/functions.html#sum) as such a function, called `add()`. Its implementation only adds two numbers.

In [281]:
def add(sum_so_far, next_number):
    """Reduce a sequence by addition."""
    return sum_so_far + next_number

Further, we create a *new* `map` object derived from `numbers` ...

In [282]:
evens_transformed = map(transform, filter(is_even, numbers))

... and loop over all *but* the first element it generates. That we capture separately as the initial `result` with the [next()](https://docs.python.org/3/library/functions.html#next) function. So, `map` objects must be *iterable* as we may loop over them.

We know that `evens_transformed` generates *six* elements. That is why we see *five* growing `result` values resembling a [cumulative sum](http://mathworld.wolfram.com/CumulativeSum.html).

In [283]:
result = next(evens_transformed)  # first element is the initial value

for number in evens_transformed:  # iterate over the remaining elements
    print(result, end=" ")  # line added for didactical purposes
    result = add(result, number)

65 210 215 252 353 

The final `result` is the same `370` as above.

In [284]:
result

370

The [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) function in the [functools](https://docs.python.org/3/library/functools.html) module in the [standard library](https://docs.python.org/3/library/index.html) provides more convenience replacing the `for`-loop. It takes two arguments in the same way as the [map()](https://docs.python.org/3/library/functions.html#map) and [filter()](https://docs.python.org/3/library/functions.html#filter) built-ins.

[reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) is **[eager](https://en.wikipedia.org/wiki/Eager_evaluation)** meaning that all computations implied by the contained `map` and `filter` "rules" are executed right away, and the code cell returns `370`. On the contrary, [map()](https://docs.python.org/3/library/functions.html#map) and [filter()](https://docs.python.org/3/library/functions.html#filter) create **[lazy](https://en.wikipedia.org/wiki/Lazy_evaluation)** `map` and `filter` objects, and we have to use the [next()](https://docs.python.org/3/library/functions.html#next) function to obtain the elements.

In [285]:
from functools import reduce

In [286]:
reduce(add, map(transform, filter(is_even, numbers)))

370

### Lambda Expressions

[map()](https://docs.python.org/3/library/functions.html#map), [filter()](https://docs.python.org/3/library/functions.html#filter), and [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) take a `function` object as their first argument, and we defined `transform()`, `is_even()`, and `add()` to be used precisely for that.

Often, such functions are used *only once* in a program. However, the primary purpose of functions is to *reuse* them. In such cases, it makes more sense to define them "anonymously" right at the position where the first argument goes.

As mentioned in [Chapter 2](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/02_functions.ipynb#Anonymous-Functions), Python provides `lambda` expressions to create `function` objects *without* a name referencing them.

So, the above `add()` function could be rewritten as a `lambda` expression like so ...

In [287]:
lambda sum_so_far, next_number: sum_so_far + next_number

<function __main__.<lambda>(sum_so_far, next_number)>

... or even shorter.

In [288]:
lambda x, y: x + y

<function __main__.<lambda>(x, y)>

With the new concepts in this section, we can rewrite the entire example in just a few lines of code *without* any `for`, `if`, and `def` statements. The resulting code is concise, easy to read, quick to modify, and even faster in execution. Most importantly, it is optimized to handle big amounts of data as *no* temporary `list` objects are materialized in memory.

In [289]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]
evens = filter(lambda x: x % 2 == 0, numbers)
transformed = map(lambda x: (x ** 2) + 1, evens)
sum(transformed)

370

If `numbers` comes as a sorted sequence of whole numbers, we may use the [range()](https://docs.python.org/3/library/functions.html#func-range) built-in and get away *without any* `list` object in memory at all!

In [290]:
numbers = range(1, 13)
evens = filter(lambda x: x % 2 == 0, numbers)
transformed = map(lambda x: (x ** 2) + 1, evens)
sum(transformed)

370

To additionally save the temporary variables, `numbers`, `evens`, and `transformed`, we write the entire computation as *one* expression.

In [291]:
sum(map(lambda x: (x ** 2) + 1, filter(lambda x: x % 2 == 0, range(1, 13))))

370

PythonTutor visualizes the differences in the number of computational steps and memory usage:
- [Version 1](http://pythontutor.com/visualize.html#code=def%20is_even%28element%29%3A%0A%20%20%20%20if%20element%20%25%202%20%3D%3D%200%3A%0A%20%20%20%20%20%20%20%20return%20True%0A%20%20%20%20return%20False%0A%0Adef%20transform%28element%29%3A%0A%20%20%20%20return%20%28element%20**%202%29%20%2B%201%0A%0Anumbers%20%3D%20list%28range%281,%2013%29%29%0A%0Aevens%20%3D%20%5B%5D%0Afor%20number%20in%20numbers%3A%0A%20%20%20%20if%20is_even%28number%29%3A%0A%20%20%20%20%20%20%20%20evens.append%28number%29%0A%0Atransformed%20%3D%20%5B%5D%0Afor%20number%20in%20evens%3A%0A%20%20%20%20transformed.append%28transform%28number%29%29%0A%0Aresult%20%3D%20sum%28transformed%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false): With `for`-loops, `if` statements, and named functions -> **116** steps
- [Version 2](http://pythontutor.com/visualize.html#code=numbers%20%3D%20range%281,%2013%29%0Aevens%20%3D%20filter%28lambda%20x%3A%20x%20%25%202%20%3D%3D%200,%20numbers%29%0Atransformed%20%3D%20map%28lambda%20x%3A%20%28x%20**%202%29%20%2B%201,%20evens%29%0Aresult%20%3D%20sum%28transformed%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false): With named `map` and `filter` objects -> **58** steps
- [Version 3](http://pythontutor.com/visualize.html#code=result%20%3D%20sum%28map%28lambda%20x%3A%20%28x%20**%202%29%20%2B%201,%20filter%28lambda%20x%3A%20x%20%25%202%20%3D%3D%200,%20range%281,%2013%29%29%29%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false): Everything in *one* expression -> **55** steps

Versions 2 and 3 are the same, except for the three additional steps required to create the temporary variables. The *major* downside of Version 1 is that, in the worst case, it may need *three times* the memory as compared to the other two versions!

An experienced Pythonista would probably go with Version 2 in a production system to keep the code readable and maintainable.

### List Comprehensions

For [map()](https://docs.python.org/3/library/functions.html#map) and [filter()](https://docs.python.org/3/library/functions.html#filter), Python provides a nice syntax appealing to people who like mathematics.

Consider again the "*A simple Filter*" example from [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#Example:-A-simple-Filter), written with combined `for` and `if` statements. So, the mapping and filtering steps happen simultaneously.

In [292]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [293]:
evens_transformed = []

for number in numbers:
    if number % 2 == 0:
        evens_transformed.append((number ** 2) + 1)

In [294]:
evens_transformed

[65, 145, 5, 37, 101, 17]

**List comprehensions**, or **list-comps** for short, are *expressions* to derive *new* `list` objects out of *existing* ones (cf., [reference](https://docs.python.org/3/reference/expressions.html#displays-for-lists-sets-and-dictionaries)). A single *expression* like below can replace the compound `for` *statement* from above.

In [295]:
[(n ** 2) + 1 for n in numbers if n % 2 == 0]

[65, 145, 5, 37, 101, 17]

A list comprehension may be used in place of any `list` object.

For example, let's add up all the elements with [sum()](https://docs.python.org/3/library/functions.html#sum). The code below *materializes* all elements in memory *before* summing them up. So,  this code might cause a `MemoryError` when executed with a bigger `numbers` list. [PythonTutor](http://pythontutor.com/visualize.html#code=numbers%20%3D%20range%281,%2013%29%0Aresult%20%3D%20sum%28%5B%28n%20**%202%29%20%2B%201%20for%20n%20in%20numbers%20if%20n%20%25%202%20%3D%3D%200%5D%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows how a `list` object exists in memory at step 17 and then "gets lost" right after. 

In [296]:
sum([(n ** 2) + 1 for n in numbers if n % 2 == 0])

370

#### Example: Nested Lists

List comprehensions may come with several `for`'s and `if`'s.

The cell below creates a `list` object that contains other `list` objects with numbers in them. The starting number in each inner `list` object is offset by `1`.

In [297]:
nested_numbers = [list(range(x, y + 1)) for x, y in zip([1, 2, 3], [7, 8, 9])]

In [298]:
nested_numbers

[[1, 2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7, 8], [3, 4, 5, 6, 7, 8, 9]]

To do something meaningful with the numbers, we have to get rid of the inner layer of `list` objects and flatten the data.

Without list comprehensions, we would probably write two nested `for`-loops.

In [299]:
flat_numbers = []

for inner_numbers in nested_numbers:
    for number in inner_numbers:
        flat_numbers.append(number)

In [300]:
flat_numbers

[1, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 9]

That translates into a list comprehension like below. The order of the `for`'s may be confusing at first but is the *same* as writing out the nested `for`-loops.

In [301]:
[number for inner_numbers in nested_numbers for number in inner_numbers]

[1, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8, 9]

Now, we may use the `list` object resulting from the list comprehension in any context we want.

As an example, we add up the flattened numbers with [sum()](https://docs.python.org/3/library/functions.html#sum). The same caveat holds as before: The `list` object passed into [sum()](https://docs.python.org/3/library/functions.html#sum) is *materialized* before the sum is calculated!

In [302]:
sum([number for inner_numbers in nested_numbers for number in inner_numbers])

105

In this particular example, however, we can exploit the fact that any sum of numbers can be expressed as the sum of sums of mutually exclusive and collectively exhaustive subsets of these numbers and get away with just *one* `for` in the list comprehension.

In [303]:
sum([sum(inner_numbers) for inner_numbers in nested_numbers])

105

#### Example: Cartesian Products

A popular use case of nested list comprehensions is applying a transformation to each $2$-tuple of the [Cartesian product](https://en.wikipedia.org/wiki/Cartesian_product) of two iterables.

For example, let's add `1` to each quotient obtained by taking the numerator from `[10, 20, 30]` and the denominator from `[40, 50, 60]`, and then find the product of all quotients. The table below visualizes the calculations: The result is the product of *nine* entries.

||**10**|**20**|**30**|
|-|-|-|-|
|**40**|1.25|1.50|1.75|
|**50**|1.20|1.40|1.60|
|**60**|1.17|1.33|1.50|

To express that in Python, we start by creating two `list` objects, `first` and `second`.

In [304]:
first = [10, 20, 30]
second = [40, 50, 60]

For a Cartesian product, we loop over *all* possible $2$-tuples where one element is drawn from `first` and the other from `second`. That is equivalent to two nested `for`-loops.

In [305]:
cartesian_product = []

for numerator in first:
    for denominator in second:
        quotient = numerator / denominator
        cartesian_product.append(quotient + 1)

cartesian_product

[1.25, 1.2, 1.1666666666666667, 1.5, 1.4, 1.3333333333333333, 1.75, 1.6, 1.5]

We translate the two `for`-loops into one list comprehensions with two `for`'s in it and use `x` and `y` as shorter variable names.

In [306]:
[(x / y) + 1 for x in first for y in second]

[1.25, 1.2, 1.1666666666666667, 1.5, 1.4, 1.3333333333333333, 1.75, 1.6, 1.5]

The order of the `for`'s is *important*: The list comprehension above divides numbers from `first` by numbers from `second`, whereas the list comprehension below does the opposite.

In [307]:
[(x / y) + 1 for x in second for y in first]

[5.0, 3.0, 2.333333333333333, 6.0, 3.5, 2.666666666666667, 7.0, 4.0, 3.0]

To find the overall product, we *unpack* the first list comprehension right into the `product()` function from the "*Packing & Unpacking*" section above.

In [308]:
product(*[(x / y) + 1 for x in first for y in second])

20.58

Alternatively, we use a `lambda` expression with the [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) function from the [functools](https://docs.python.org/3/library/functools.html) module.

In [309]:
reduce(lambda x, y: x * y, [(x / y) + 1 for x in first for y in second])

20.58

While this example is stylized, Cartesian products are hidden in many applications, and it shows how the various language features introduced in this chapter can be seamlessly combined to process sequential data.

### Generator Expressions

Pythonistas would forgo materialized `list` objects, and, thus, also list comprehensions, all together, and use a more memory-efficient approach with **[generator expressions](https://docs.python.org/3/reference/expressions.html#generator-expressions)**, or **genexps** for short. Syntactically, they work like list comprehensions except that parentheses replace the brackets.

Let's go back to the original example in this section and find the transformation $y := x^2 + 1$ of all even elements in `numbers`.

In [310]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

To filter and transform `numbers`, we wrote this list comprehension above ...

In [311]:
[(n ** 2) + 1 for n in numbers if n % 2 == 0]

[65, 145, 5, 37, 101, 17]

... that now becomes a generator expression.

In [312]:
((n ** 2) + 1 for n in numbers if n % 2 == 0)

<generator object <genexpr> at 0x7f790c3a55e8>

We can think of it as yet another "rule" in memory that knows how to generate the individual objects in a series one by one. Whereas a list comprehension materializes its elements in memory *when* it is evaluated, the opposite holds for generator expressions, and *no* object is created in memory except the "rule" itself. Because of this behavior, we describe generator expressions as *lazy* and list comprehensions as *eager*.

So, to materialize all elements specified by a generator expression, we revert to the [list()](https://docs.python.org/3/library/functions.html#func-list) built-in.

In [313]:
list(((n ** 2) + 1 for n in numbers if n % 2 == 0))

[65, 145, 5, 37, 101, 17]

Whenever a generator expression is the only argument to a function, we may leave out the parentheses.

In [314]:
list((n ** 2) + 1 for n in numbers if n % 2 == 0)

[65, 145, 5, 37, 101, 17]

A common use case is to reduce the elements into a single object instead, for example, by adding them up with [sum()](https://docs.python.org/3/library/functions.html#sum). [PythonTutor](http://pythontutor.com/visualize.html#code=numbers%20%3D%20range%281,%2013%29%0Asum_with_list%20%3D%20sum%28%5B%28n%20**%202%29%20%2B%201%20for%20n%20in%20numbers%20if%20n%20%25%202%20%3D%3D%200%5D%29%0Asum_with_gen%20%3D%20sum%28%28n%20**%202%29%20%2B%201%20for%20n%20in%20numbers%20if%20n%20%25%202%20%3D%3D%200%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows how the code cell below does *not* create a temporary `list` object in memory, whereas a list comprehension would (cf., step 17).

In [315]:
sum((n ** 2) + 1 for n in numbers if n % 2 == 0)

370

Let's assign the object returned from a generator expression to a variable and inspect it.

In [316]:
gen = ((n ** 2) + 1 for n in numbers if n % 2 == 0)

In [317]:
gen

<generator object <genexpr> at 0x7f790c3a5a20>

Unsurprisingly, generator expressions create objects of type `generator`.

In [318]:
type(gen)

generator

With the [next()](https://docs.python.org/3/library/functions.html#next) function, we can retrieve the generated elements one by one.

In [319]:
next(gen)

65

In [320]:
next(gen)

145

In [321]:
next(gen)

5

In [322]:
next(gen)

37

In [323]:
next(gen)

101

In [324]:
next(gen)

17

Once a `generator` object runs out of elements, it raises a `StopIteration` exception. We say that the `generator` object is **exhausted**, and to loop over its elements again, we must create a *new* one.

In [325]:
next(gen)

StopIteration: 

In [326]:
next(gen)

StopIteration: 

Calling the [next()](https://docs.python.org/3/library/functions.html#next) function repeatedly with the *same* `generator` object as the argument is essentially what a `for`-loop automates for us. So, `generator` objects are *iterable*.

In [327]:
for number in ((n ** 2) + 1 for n in numbers if n % 2 == 0):
    print(number, end=" ")

65 145 5 37 101 17 

#### Example: Nested Lists (revisited)

If we are only interested in a *reduction* of `nested_numbers` into a single statistic, as the overall sum in the "*Nested Lists*" example, we should replace lists or list comprehensions with generator expressions wherever possible.

The result is the *same*, but no intermediate lists are materialized! That makes our code scale to larger amounts of data and uses the available hardware more efficiently.

Let's adapt the example but keep `nested_numbers` unchanged for now.

In [328]:
nested_numbers = [list(range(x, y + 1)) for x, y in zip([1, 2, 3], [7, 8, 9])]

In [329]:
nested_numbers

[[1, 2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7, 8], [3, 4, 5, 6, 7, 8, 9]]

We leave out the brackets and keep everything else as-is: The argument to [sum()](https://docs.python.org/3/library/functions.html#sum), a list comprehension in the initial implementation above, becomes a generator expression.

In [330]:
sum(number for inner_numbers in nested_numbers for number in inner_numbers)

105

That also holds for the alternative formulation as a sum of sums.

In [331]:
sum(sum(inner_numbers) for inner_numbers in nested_numbers)

105

Because `nested_numbers` has an internal structure, we can make it **memoryless** by expressing it as a generator expression derived from `range` objects. [PythonTutor](http://pythontutor.com/visualize.html#code=nested_numbers%20%3D%20%28%28range%28x,%20y%20%2B%201%29%29%20for%20x,%20y%20in%20zip%28range%281,%204%29,%20range%287,%2010%29%29%29%0Aresult%20%3D%20sum%28number%20for%20inner_numbers%20in%20nested_numbers%20for%20number%20in%20inner_numbers%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) confirms that no `list` object materializes at any point in time.

In [332]:
nested_numbers = ((range(x, y + 1)) for x, y in zip(range(1, 4), range(7, 10)))

In [333]:
nested_numbers

<generator object <genexpr> at 0x7f790c3a5b10>

In [334]:
sum(number for inner_numbers in nested_numbers for number in inner_numbers)

105

We must be careful when assigning a `generator` object to a variable: If we use `nested_numbers` again, for example, in the alternative formulation below, [sum()](https://docs.python.org/3/library/functions.html#sum) returns `0` because `nested_numbers` is exhausted after executing the previous code cell. [PythonTutor](http://pythontutor.com/visualize.html#code=nested_numbers%20%3D%20%28%28range%28x,%20y%20%2B%201%29%29%20for%20x,%20y%20in%20zip%28range%281,%204%29,%20range%287,%2010%29%29%29%0Aresult%20%3D%20sum%28number%20for%20inner_numbers%20in%20nested_numbers%20for%20number%20in%20inner_numbers%29%0Ano_result%20%3D%20sum%28sum%28inner_numbers%29%20for%20inner_numbers%20in%20nested_numbers%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) also shows that.

In [335]:
sum(sum(inner_numbers) for inner_numbers in nested_numbers)

0

#### Example: Cartesian Products (revisited)

Let's also rewrite the "*Cartesian Products*" example from above with generator expressions.

As a first optimization, we replace the materialized `list` objects, `first` and `second`, with memoryless `range` objects.

In [336]:
first = range(10, 31, 10)  # = [10, 20, 30]
second = range(40, 61, 10)  # = [40, 50, 60]

Now, the first of the two alternatives may be more appealing to many readers. In general, many practitioners seem to dislike `lambda` expressions.

The code cell below *unpacks* the elements produced by `((x / y) + 1 for x in first for y in second)` into the `product()` function from the "*Packing & Unpacking*" section above. However, inside `product()`, the elements are *packed* into `args`, a materialized `tuple` object. So, all the memory efficiency gained with the generator expression is voided! [PythonTutor](http://pythontutor.com/visualize.html#code=def%20product%28*args%29%3A%0A%20%20%20%20result%20%3D%20args%5B0%5D%0A%20%20%20%20for%20arg%20in%20args%5B1%3A%5D%3A%0A%20%20%20%20%20%20%20%20result%20*%3D%20arg%0A%20%20%20%20return%20result%0A%0Afirst%20%3D%20range%2810,%2031,%2010%29%0Asecond%20%3D%20range%2840,%2061,%2010%29%0A%0Aresult%20%3D%20product%28*%28%28x%20/%20y%29%20%2B%201%20for%20x%20in%20first%20for%20y%20in%20second%29%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) shows how a `tuple` object exists in steps 38-58.

In [337]:
product(*((x / y) + 1 for x in first for y in second))

20.58

On the contrary, the solution with the [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) function from the [functools](https://docs.python.org/3/library/functools.html) module and the `lambda` expression works *without* all elements materialized at the same time, and [PythonTutor](http://pythontutor.com/visualize.html#code=from%20functools%20import%20reduce%0A%0Afirst%20%3D%20range%2810,%2031,%2010%29%0Asecond%20%3D%20range%2840,%2061,%2010%29%0A%0Aresult%20%3D%20reduce%28%0A%20%20%20%20lambda%20x,%20y%3A%20x%20*%20y,%0A%20%20%20%20%28%28x%20/%20y%29%20%2B%201%20for%20x%20in%20first%20for%20y%20in%20second%29%0A%29&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) confirms that. So, only the second alternative is truly memory-efficient.

In [338]:
reduce(lambda x, y: x * y, ((x / y) + 1 for x in first for y in second))

20.58

In summary, we learn from this example that unpacking generator expressions *may* be a *bad* idea.

### Tuple Comprehensions

There is no syntax to derive *new* `tuple` objects out of existing ones. However, we can mimic such a construct by combining the [tuple()](https://docs.python.org/3/library/functions.html#func-tuple) built-in with a generator expression.

So, to convert the list comprehension `[(n ** 2) + 1 for n in numbers if n % 2 == 0]` from above into a "tuple comprehension," we write the following.

In [339]:
tuple((n ** 2) + 1 for n in numbers if n % 2 == 0)

(65, 145, 5, 37, 101, 17)

### Boolean Reducers

Besides [min()](https://docs.python.org/3/library/functions.html#min), [max()](https://docs.python.org/3/library/functions.html#max), and [sum()](https://docs.python.org/3/library/functions.html#sum), Python provides two boolean reduce functions: [all()](https://docs.python.org/3/library/functions.html#all) and [any()](https://docs.python.org/3/library/functions.html#any).

Let's look at straightforward examples involving `numbers` again.

In [340]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

[all()](https://docs.python.org/3/library/functions.html#all) takes an *iterable* argument and returns `True` if *all* elements are *truthy*.

For example, let's check if the square of each element in `numbers` is below `100` or `150`, respectively. We express the computation with a generator expression passed as the only argument to [all()](https://docs.python.org/3/library/functions.html#all).

In [341]:
all(x ** 2 < 100 for x in numbers)

False

In [342]:
all(x ** 2 < 150 for x in numbers)

True

[all()](https://docs.python.org/3/library/functions.html#all) can be viewed as syntactic sugar replacing a `for`-loop: Internally, [all()](https://docs.python.org/3/library/functions.html#all) implements the *short-circuiting* strategy from [Chapter 3](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/03_conditionals.ipynb#Short-Circuiting), and we mimic that by testing for the *opposite* condition in the `if` statement and leaving the `for`-loop early with the `break` statement. In the worst case, if `threshold` were, for example, `150`, we would loop over *all* elements in the *iterable*, which must be *finite* for the code to work. So, [all()](https://docs.python.org/3/library/functions.html#all) is a *linear search* in disguise.

In [343]:
threshold = 100

for number in numbers:
    if number ** 2 >= threshold:  # = the opposite of what we are checking for
        all_below_threshold = False
        break
else:
    all_below_threshold = True

all_below_threshold

False

The documentation of [all()](https://docs.python.org/3/library/functions.html#all) shows in another way what it does with code: By placing a `return` statement inside the `for`-loop of a function's body, iteration is stopped prematurely once an element does *not* meet the condition. That is the familiar *early exit* pattern at work.

In [344]:
def all_alt(iterable):
    """Alternative implementation of the built-in all() function."""
    for element in iterable:
        if not element:  # = the opposite of what we are checking for
            return False
    return True

In [345]:
all_alt(x ** 2 < 100 for x in numbers)

False

In [346]:
all_alt(x ** 2 < 150 for x in numbers)

True

Similarly, [any()](https://docs.python.org/3/library/functions.html#any) checks if *at least* one element in the *iterable* argument is *truthy*.

To continue the example, let's check if the square of *any* element in `numbers` is above `100` or `150`, respectively.

In [347]:
any(x ** 2 > 100 for x in numbers)

True

In [348]:
any(x ** 2 > 150 for x in numbers)

False

Expressed with a `for`-loop, the implementation below reveals that [any()](https://docs.python.org/3/library/functions.html#any) follows the *short-circuiting* strategy as well. Here, we do *not* need to check for the opposite condition.

In [349]:
threshold = 100

for number in numbers:
    if number ** 2 > threshold:
        any_above_threshold = True
        break
else:
    any_above_threshold = False

any_above_threshold

True

The alternative formulation in the documentation of [any()](https://docs.python.org/3/library/functions.html#any) is straightforward.

In [350]:
def any_alt(iterable):
    """Alternative implementation of the built-in any() function."""
    for element in iterable:
        if element:
            return True
    return False

In [351]:
any_alt(x ** 2 > 100 for x in numbers)

True

In [352]:
any_alt(x ** 2 > 150 for x in numbers)

False

### Example: Averaging Even Numbers (revisited)

With the new concepts in this chapter, let's rewrite the book's introductory "*Averaging Even Numbers*" example in [Chapter 1](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/01_elements.ipynb#Example:-Averaging-Even-Numbers) such that it efficiently handles a large sequence of numbers.

We assume the `average_evens()` function below is called with a *finite* and *iterable* object, which generates a "stream" of numeric objects that can be cast as `int` objects because the idea of even and odd numbers only makes sense in the context of whole numbers.

The generator expression `(int(n) for n in numbers)` implements the type casting, and when it is evaluated, *nothing* happens except that a `generator` object is stored in `integers`. Then, with the [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) function from the [functools](https://docs.python.org/3/library/functools.html) module, we *simultaneously* add up *and* count the even numbers produced by the inner generator expression `((n, 1) for n in integers if n % 2 == 0)`. That results in a `generator` object producing `tuple` objects consisting of the next *even* number in line and `1`. Two such `tuple` objects are then iteratively passed to the `lambda` expression as the `x` and `y` arguments. `x` represents the total and the count of the even numbers processed so far, while `y`'s first element, `y[0]`, is the next even number to be added to the running total. The result of the [reduce()](https://docs.python.org/3/library/functools.html#functools.reduce) function is again a `tuple` object, namely the final `total` and `count`. Lastly, we calculate the simple average.

In summary, the implementation of `average_evens()` does *not* keep materialized `list` objects internally like its predecessors from [Chapter 2](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/02_functions.ipynb), but processes the elements of the `numbers` argument on a one-by-one basis.

In [353]:
def average_evens(numbers):
    """Calculate the average of all even integers.

    Args:
        numbers (iterable): a finite stream of numbers;
            may be integers or floats; floats are truncated

    Returns:
        float: average
    """
    integers = (int(n) for n in numbers)
    total, count = reduce(
        lambda x, y: (x[0] + y[0], x[1] + y[1]),
        ((n, 1) for n in integers if n % 2 == 0)
    )
    return total / count

In [354]:
average_evens([7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4])

7.0

An argument generating `float` objects works as well.

In [355]:
average_evens([7., 11., 8., 5., 3., 12., 2., 6., 9., 10., 1., 4.])

7.0

To show that `average_evens()` can process a **stream** of data, we simulate `10_000_000` randomly drawn integers between `0` and `100` with the [randint()](https://docs.python.org/3/library/random.html#random.randint) function from the [random](https://docs.python.org/3/library/random.html) module. We use a generator expression derived from a `range` object as the `numbers` argument. So, at *no* point in time is there a materialized `list` or `tuple` object in memory. The result approaching `50` tells us that [randint()](https://docs.python.org/3/library/random.html#random.randint) must be based on a uniform distribution.

In [356]:
import random

In [357]:
random.seed(42)

In [358]:
average_evens(random.randint(0, 100) for _ in range(10_000_000))

49.994081434519636

To show that `average_evens()` filters out odd numbers, we simulate another stream of `10_000_000` randomly drawn odd integers between `1` and `99`. As no function in the [random](https://docs.python.org/3/library/random.html) module does that "out of the box," we must be creative: Doubling a number drawn from `random.randint(0, 49)` results in an even number between `0` and `98`, and adding `1` makes it odd. Then, `average_evens()` raises a `TypeError`, essentially because `(int(n) for n in numbers)` does not generate any element.

In [359]:
average_evens(2 * random.randint(0, 49) + 1 for _ in range(10_000_000))

TypeError: reduce() of empty sequence with no initial value

## Iterators vs. Iterables

In the "*Collections vs. Sequences*" section above, we studied the three and four *behaviors* of collections and sequences. The latter two are *abstract* ideas, and we mainly use them to classify *concrete* data types.

Similarly, we have introduced data types in this chapter that all share the "behavior" of modeling some "rule" in memory to generate objects "on the fly:" They are the `map`, `filter`, and `generator` types. Their main commonality is supporting the built-in [next()](https://docs.python.org/3/library/functions.html#next) function. In computer science terminology, such data types are called **[iterators](https://en.wikipedia.org/wiki/Iterator)**, and the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module formalizes them with the `Iterator` ABC.

So, an example of an iterator is `evens_transformed` below, an object of type `generator`.

In [360]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [361]:
evens_transformed = ((x ** 2) + 1 for x in numbers if x % 2 == 0)

Let's first confirm that `evens_transformed` is indeed an `Iterator`, "abstractly speaking."

In [362]:
isinstance(evens_transformed, abc.Iterator)

True

In Python, iterators are *always* also iterables. The reverse does *not* hold! To be precise, iterators are *specializations* of iterables. That is what the "Inherits from" columns means in the [collections.abc](https://docs.python.org/3/library/collections.abc.html) module's documentation.

In [363]:
isinstance(evens_transformed, abc.Iterable)

True

Furthermore, we revise our definition of *iterables* from above: Just as we defined an *iterator* to be an object that supports the [next()](https://docs.python.org/3/library/functions.html#next) function, we define an *iterable* to be an object that supports the built-in [iter()](https://docs.python.org/3/library/functions.html#iter) function.

The confused reader may now be wondering how the two concepts relate to each other.

In short, the [iter()](https://docs.python.org/3/library/functions.html#iter) function is the general way to create an *iterator* object out of a given *iterable* object. In real-world code, we hardly ever see [iter()](https://docs.python.org/3/library/functions.html#iter) as Python calls it for us in the background. Then, the *iterator* object manages the iteration over the *iterable* object.

For illustration, let's do that ourselves and create *two* iterators out of the iterable `numbers` and see what we can do with them.

In [364]:
iterator1 = iter(numbers)

In [365]:
iterator2 = iter(numbers)

`iterator1` and `iterator2` are of type `list_iterator`.

In [366]:
type(iterator1)

list_iterator

*Iterators* are useful for only *one* operation: Get the next object from the associated *iterable*.

By calling [next()](https://docs.python.org/3/library/functions.html#next) three times with `iterator1` as the argument, we obtain the first three elements of `numbers`.

In [367]:
next(iterator1), next(iterator1), next(iterator1)

(7, 11, 8)

`iterator1` and `iterator2` keep their *states* separate. So, we could "manually" loop over an *iterable* in parallel.

In [368]:
next(iterator1), next(iterator2)

(5, 7)

We can also play a "trick" and exchange some elements in `numbers`. `iterator1` and `iterator2` do *not* see these changes and present us with the new elements. So, *iterators* not only have state on their own but also keep this separate from the underlying *iterable*.

In [369]:
numbers[1], numbers[4] = 99, 99

In [370]:
next(iterator1), next(iterator2)

(99, 99)

Let's re-assign the elements in `numbers` so that they are in order. Now, the numbers returned from [next()](https://docs.python.org/3/library/functions.html#next) also tell us how often [next()](https://docs.python.org/3/library/functions.html#next) was called with `iterator1` or `iterator2`. We conclude that `list_iterator` objects must be keeping track of the *last* index obtained from the underlying *iterable*.

In [371]:
numbers[:] = list(range(1, 13))

In [372]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [373]:
next(iterator1), next(iterator2)

(6, 3)

With the concepts introduced in this section, we can now understand the first sentence in the documentation on the [zip()](https://docs.python.org/3/library/functions.html#zip) built-in better: "Make an *iterator* that aggregates elements from each of the *iterables*."

Because *iterators* are always also *iterables*, we pass `iterator1` and `iterator2` as arguments to [zip()](https://docs.python.org/3/library/functions.html#zip).

The returned `zipper` object is of type `zip` and, "abstractly speaking," an `Iterator` as well.

In [374]:
zipper = zip(iterator1, iterator2)

In [375]:
zipper

In [376]:
type(zipper)

zip

In [377]:
isinstance(zipper, abc.Iterator)

True

So far, we have always used [zip()](https://docs.python.org/3/library/functions.html#zip) with a `for` statement and looped over it. That was our earlier definition of an *iterable*. Our revised definition in this section states that an *iterable* is an object that supports the [iter()](https://docs.python.org/3/library/functions.html#iter) function. So, let's see what happens if we pass `zipper` to [iter()](https://docs.python.org/3/library/functions.html#iter).

In [378]:
zipper_iterator = iter(zipper)

In [379]:
zipper_iterator

`zipper_iterator` references the *same* object as `zipper`! That holds for *iterators* in general: Any *iterator* created from an existing *iterator* with [iter()](https://docs.python.org/3/library/functions.html#iter) is the *iterator* itself.

In [380]:
zipper is zipper_iterator

True

The Python core developers made that design decision so that *iterators* may also be looped over.

The `for`-loop below prints out *six* more `tuple` objects derived from the now ordered `numbers` because the `iterator1` object hidden inside `zipper` already returned the first *six* elements. So, the respective first elements of the `tuple` objects printed range from `7` to `12`. Similarly, as `iterator2` already provided *three* elements from `numbers`, we see the respective second elements in the range from `4` to `9`.

In [381]:
for x, y in zipper:
    print(x, ">", y, end="   ")

7 > 4   8 > 5   9 > 6   10 > 7   11 > 8   12 > 9   

`zipper` is now *exhausted*. So, the `for`-loop below does *not* make any iteration at all.

In [382]:
for x, y in zipper:
    print(x, ">", y, end="   ")

We verify that `iterator1` is exhausted by passing it to [next()](https://docs.python.org/3/library/functions.html#next) again, which raises a `StopIteration` exception.

In [383]:
next(iterator1)

StopIteration: 

On the contrary, `iterator2` is *not* yet exhausted.

In [384]:
next(iterator2)

10

Understanding *iterators* and *iterables* is helpful for any data science practitioner that deals with large amounts of data. Even without that, these two terms occur everywhere in Python-related texts and documentation.

### The `for` Statement (revisited)

In [Chapter 4](https://nbviewer.jupyter.org/github/webartifex/intro-to-python/blob/master/04_iteration.ipynb#The-for-Statement), we argue that the `for` statement is syntactic sugar, replacing the `while` statement in many scenarios. In particular, a `for`-loop saves us two tasks: Managing an index variable *and* obtaining the individual elements by indexing. In this sub-section, we look at a more realistic picture, using the new terminology as well.

Let's print out the elements of a `list` object as the *iterable* to be looped over.

In [385]:
iterable = [0, 1, 2, 3, 4]

In [386]:
for element in iterable:
    print(element, end=" ")

0 1 2 3 4 

Our previous and equivalent formulation with a `while` statement is like so.

In [387]:
index = 0
while index < len(iterable):
    element = iterable[index]
    print(element, end=" ")
    index += 1
del index

0 1 2 3 4 

What happens behind the scenes in the Python interpreter is shown below.

First, Python calls [iter()](https://docs.python.org/3/library/functions.html#iter) with the `iterable` to be looped over, and obtains an `iterator`. That contains the entire logic of how the `iterable` is looped over. In particular, the `iterator` may or may not pick the `iterable`'s elements in a predictable order. That is up to the "rule" it models.

Second, Python enters an *indefinite* `while`-loop. It tries to obtain the next element with [next()](https://docs.python.org/3/library/functions.html#next). If that succeeds, the `for`-loop's code block is executed. Below, that code is placed within the `else`-clause that runs only if *no* exception is raised in the `try`-clause. Then, Python jumps into the next iteration and tries to obtain the next element from the `iterator`, and so on. Once the `iterator` is exhausted, it raises a `StopIteration` exception, and Python leaves the `while`-loop with the `break` statement.

In [388]:
iterator = iter(iterable)

while True:
    try:
        element = next(iterator)
    except StopIteration:
        break
    else:
        print(element, end=" ")

0 1 2 3 4 

### sorted() vs. reversed()

Now that we know the concept of an *iterator*, let's compare some of the built-ins introduced in this chapter in detail and make sure we understand what is going on in memory. This sub-section is thus a great summary of this chapter as well.

We use two simple examples, `numbers` and `memoryless`, to guide us through the discussion. `numbers` creates *thirteen* objects in memory and `memoryless` only *one* (cf., [PythonTutor](http://www.pythontutor.com/visualize.html#code=numbers%20%3D%20%5B7,%2011,%208,%205,%203,%2012,%202,%206,%209,%2010,%201,%204%5D%0Amemoryless%20%3D%20range%281,%2013%29&cumulative=false&curInstr=2&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false))

In [389]:
numbers = [7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [390]:
memoryless = range(1, 13)

The [sorted()](https://docs.python.org/3/library/functions.html#sorted) function takes a *finite* and *iterable* object as its argument and *materializes* its elements into a *new* `list` object that is returned.

The argument may already be materialized, as is the case with `numbers`, but could also be an *iterator* that generates *new* objects, such as `memoryless`. In both cases, we end up with materialized `list` objects with the elements sorted in *forward* order (cf., [PythonTutor](http://www.pythontutor.com/visualize.html#code=numbers%20%3D%20%5B7,%2011,%208,%205,%203,%2012,%202,%206,%209,%2010,%201,%204%5D%0Amemoryless%20%3D%20range%281,%2013%29%0Aresult1%20%3D%20sorted%28numbers%29%0Aresult2%20%3D%20sorted%28memoryless%29&cumulative=false&curInstr=4&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)).

In [391]:
sorted(numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [392]:
sorted(memoryless)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

By adding a keyword-only argument `reverse=True`, the materialized `list` objects are sorted in *reverse* order (cf., [PythonTutor](http://www.pythontutor.com/visualize.html#code=numbers%20%3D%20%5B7,%2011,%208,%205,%203,%2012,%202,%206,%209,%2010,%201,%204%5D%0Amemoryless%20%3D%20range%281,%2013%29%0Aresult1%20%3D%20sorted%28numbers,%20reverse%3DTrue%29%0Aresult2%20%3D%20sorted%28memoryless,%20reverse%3DTrue%29&cumulative=false&curInstr=4&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)).

In [393]:
sorted(numbers, reverse=True)

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [394]:
sorted(memoryless, reverse=True)

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

The order in `numbers` remains *unchanged*, and `memoryless` is still *not* materialized.

In [395]:
numbers

[7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [396]:
memoryless

range(1, 13)

The [reversed()](https://docs.python.org/3/library/functions.html#reversed) built-in takes a *sequence* object as its argument and returns an *iterator*. The argument must be *finite* and *reversible* (i.e., *iterable* in *reverse* order) as otherwise [reversed()](https://docs.python.org/3/library/functions.html#reversed) could neither determine the last element that becomes the first nor loop in a *predictable* backward fashion. [PythonTutor](http://www.pythontutor.com/visualize.html#code=numbers%20%3D%20%5B7,%2011,%208,%205,%203,%2012,%202,%206,%209,%2010,%201,%204%5D%0Amemoryless%20%3D%20range%281,%2013%29%0Aiterator1%20%3D%20reversed%28numbers%29%0Aiterator2%20%3D%20reversed%28memoryless%29&cumulative=false&curInstr=4&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false) confirms that [reversed()](https://docs.python.org/3/library/functions.html#reversed) does *not* materialize any elements but only returns an *iterator*.

**Side Note**: Even though `range` objects, like `memoryless` here, do *not* "contain" references to other objects, they count as *sequence* types, and as such, they are also *container* types. The `in` operator works with `range` objects because we can always cast the object to be checked as an `int` and check if that lies within the `range` object's *start* and *stop* values, taking a potential *step* value into account (cf., this [blog post](https://treyhunner.com/2018/02/python-range-is-not-an-iterator/) for more details on the [range()](https://docs.python.org/3/library/functions.html#func-range) built-in).

In [397]:
reversed(numbers)

In [398]:
reversed(memoryless)

To materialize the elements, we can pass the returned *iterators* to, for example, the [list()](https://docs.python.org/3/library/functions.html#func-list) or [tuple()](https://docs.python.org/3/library/functions.html#func-tuple) built-ins. That creates *new* `list` and `tuple` objects (cf., [PythonTutor](http://www.pythontutor.com/visualize.html#code=numbers%20%3D%20%5B7,%2011,%208,%205,%203,%2012,%202,%206,%209,%2010,%201,%204%5D%0Amemoryless%20%3D%20range%281,%2013%29%0Aresult1%20%3D%20list%28reversed%28numbers%29%29%0Aresult2%20%3D%20tuple%28reversed%28memoryless%29%29&cumulative=false&curInstr=4&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)).

To reiterate some more new terminology from this chapter, we describe [reversed()](https://docs.python.org/3/library/functions.html#reversed) as *lazy*, whereas [list()](https://docs.python.org/3/library/functions.html#func-list) and [tuple()](https://docs.python.org/3/library/functions.html#func-tuple) are *eager*. The former has no significant side effect in memory, while the latter may require a lot of memory.

In [399]:
list(reversed(numbers))

[4, 1, 10, 9, 6, 2, 12, 3, 5, 8, 11, 7]

In [400]:
tuple(reversed(memoryless))

(12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)

Of course, we can also loop over the returned *iterators* instead.

That works because *iterators* are always *iterables*; in particular, as the previous "*The for Statement (revisited)*" sub-section explains, the `for`-loops below call `iter(reversed(numbers))` and `iter(reversed(memoryless))` behind the scenes. However, the *iterators* returned by [iter()](https://docs.python.org/3/library/functions.html#iter) are the *same* as the `reversed(numbers)` and `reversed(memoryless)` iterators passed in! In summary, the `for`-loops below involve many subtleties that together make Python the expressive language it is.

In [401]:
for number in reversed(numbers):
    print(number, end=" ")

4 1 10 9 6 2 12 3 5 8 11 7 

In [402]:
for element in reversed(memoryless):
    print(element, end=" ")

12 11 10 9 8 7 6 5 4 3 2 1 

As with [sorted()](https://docs.python.org/3/library/functions.html#sorted), the [reversed()](https://docs.python.org/3/library/functions.html#reversed) built-in does *not* mutate its argument.

In [403]:
numbers

[7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [404]:
memoryless

range(1, 13)

To point out the potentially obvious, we compare the results of *sorting* `numbers` in *reverse* order with *reversing* it: These are *different* concepts!

In [405]:
numbers

[7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

In [406]:
sorted(numbers, reverse=True)

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [407]:
list(reversed(numbers))

[4, 1, 10, 9, 6, 2, 12, 3, 5, 8, 11, 7]

Whereas both [sorted()](https://docs.python.org/3/library/functions.html#sorted) and [reversed()](https://docs.python.org/3/library/functions.html#reversed) do *not* mutate their arguments, the *mutable* `list` type comes with two methods, [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) and `reverse()`, that implement the same logic but mutate an object, like `numbers` below, *in place*. To indicate that all changes occur *in place*, the [sort()](https://docs.python.org/3/library/stdtypes.html#list.sort) and `reverse()` methods always return `None`, which is not shown.

In [408]:
numbers

[7, 11, 8, 5, 3, 12, 2, 6, 9, 10, 1, 4]

The `reverse()` method is *eager*, as opposed to the *lazy* [reversed()](https://docs.python.org/3/library/functions.html#reversed) built-in. That means the mutations causes by the `reverse()` method are written into memory right away.

In [409]:
numbers.reverse()

In [410]:
numbers

[4, 1, 10, 9, 6, 2, 12, 3, 5, 8, 11, 7]

*Sorting* `numbers` in *reverse* order below is of course still *different* from simply *reversing* it above.

In [411]:
numbers.sort(reverse=True)

In [412]:
numbers

[12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [413]:
numbers.sort()

In [414]:
numbers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

## TL;DR

**Sequences** are an *abstract* concept that summarizes *four* behaviors an object may or may not exhibit. Sequences are
- **finite** and
- **ordered**
- **containers** that we may
- **loop over**.

Examples are the `list`, `tuple`, but also the `str` types.

Objects that exhibit all behaviors *except* being ordered are referred to as **collections**.

The objects inside a sequence are called its **elements** and may be labeled with a unique **index**, an `int` object in the range $0 \leq \text{index} < \lvert \text{sequence} \rvert$.

`list` objects are **mutable**. That means we can change the references to the other objects it contains, and, in particular, re-assign them.

On the contrary, `tuple` objects are like **immutable** lists: We can use them in place of any `list` object as long as we do *not* need to mutate it. Often, `tuple` objects are also used to model **records** of related **fields**.

The tasks we do with sequential data follow the **map-filter-reduce paradigm**: We apply the same transformation to all elements, filter some of them out, and calculate summary statistics from the remaining ones.

An essential idea in this chapter is that, in many situations, we need *not* have all the data **materialized** in memory. Instead, **iterators** allow us to process sequential data on a one-by-one basis.

Examples for iterators are the `map`, `filter`, and `generator` types.